### ISSUE TITLE
summaryFormat=JSON produces invalid JSON

### ISSUE THREAD

**Issue by glennklockwood** [hpc/ior#102]
The JSON output driver for IOR could use some improvement.  With the default options, the first line of output results in an invalid json blob:

```
$ mpirun -np 2 ./test/_inst/bin/ior -O summaryFormat=json
IOR-3.2.0: MPI Coordinated Test of Parallel I/O
{
  "Began": "Mon Oct  8 16:07:19 2018", 
  "Command line": "./test/_inst/bin/ior -O summaryFormat=json", 
...

$ mpirun -np 2 ./test/_inst/bin/ior -O summaryFormat=json | python -mjson.tool
Expecting value: line 1 column 1 (char 0)
```

Skipping that results in some more problems.  It looks like the 

```
$ mpirun -np 2 ./test/_inst/bin/ior -O summaryFormat=json | gtail --lines=+2 | python -mjson.tool
Expecting ',' delimiter: line 124 column 1 (char 3058)
```

Something after the "Results" block gets messed up, resulting in a stray "max" block and an invalid "summary" block:

```
            {   
        "access": "remove", 
        "totalTime": 0.0002
      }   
]
]
, 
  "max": {
    "writeMiB": 1658.4832, 
    "writeMB": 1739.0457, 
    "readMiB": 1266.5873, 
    "readMB": 1328.1131
  }

}
]
, 
"summary": [
[ ]

}

}
```

It then appears that the contents of the summary block are printed out after the top-level block is closed.

I'll also add that adding verbosity (`-v`) results in a lot more bare text being injected into stdout and interfering with the JSON output.

**Comment by JulianKunkel** [comment]
I commited 3b5f4fc00271146e3a103e42a8e6bd9e6c1eab which fixes the issue. I intended to do this in a "hotfix" branch but it was just little change.
