### ISSUE TITLE
mdtest should verify data on read

### ISSUE THREAD

**Issue by johnbent** [hpc/ior#111]
Andreas Dilger: "I wonder if mdtest-hard is doing data verification for the small files (e.g. write the filename+per-run hash into the last bytes of the file, similar to what IOR does)?  that would be good verification of correctness, and avoid some amount of cheating (AFAIK ZFS can compress all zero-filled blocks to a special checksum and not write anything to disk)"
John Bent: "Hmm, checked the code; it doesn't appear to verify.  I'll open an issue.  Thanks!"

**Comment by johnbent** [comment]
Andreas: "IOR has -R to do read-verify, and -G to specify the data timestamp if the read step is separate from the write step (which it would be in the mdtest-hard case).  for debugging, this is useful to ensure that the file data was actually written in the particular test run rather than stale data that might have been previously written"

**Comment by JulianKunkel** [comment]
-X option had been added to mdtest a while ago.
