### ISSUE TITLE
mdtest stat a file which is not created

### ISSUE THREAD

**Issue by lee-fan** [hpc/ior#112]
The problem is that mdtest stat a file which is not created previously.

the command i was using: mdtest -C -T -F -V=3 -d /mnt/mdtest -i 3 -I 10 -z 1 -b 2 -L -u
The following is the output from mdtest:
V-1: Entering PrintTimestamp...
-- started at 11/20/2018 14:23:50 --

mdtest-1.9.3 was launched with 1 total task(s) on 1 node(s)
Command line used: mdtest "-C" "-T" "-F" "-V=3" "-d" "/mnt/mdtest" "-i" "3" "-I" "10" "-z" "1" "-b" "2" "-L" "-u"
V-1: Entering parse_dirpath...
V-1: Entering valid_tests...
api                     : POSIX
barriers                : True
collective_creates      : False
create_only             : True
dirpath(s):
	/mnt/mdtest
dirs_only               : False
read_bytes              : 0
read_only               : False
first                   : 1
files_only              : True
iterations              : 3
items_per_dir           : 10
last                    : 0
leaf_only               : True
items                   : 0
nstride                 : 0
pre_delay               : 0
remove_only             : True
random_seed             : 0
stride                  : 1
shared_file             : False
time_unique_dir_overhead: False
stone_wall_timer_seconds: 0
stat_only               : True
unique_dir_per_task     : True
write_bytes             : 0
sync_file               : False
depth                   : 1
V-3: main (before display_freespace): testdirpath is "/mnt/mdtest"
V-1: Entering display_freespace...
V-3: testdirpath is "/mnt/mdtest"
V-3: Before show_file_system_size, dirpath is "/mnt"
V-1: Entering show_file_system_size...
Path: /mnt
FS: 517.6 GiB   Used FS: 39.4%   Inodes: 32.9 Mi   Used Inodes: 0.5%
V-3: After show_file_system_size, dirpath is "/mnt"
V-3: main (after display_freespace): testdirpath is "/mnt/mdtest"

1 tasks, 30 files

   Operation               Duration              Rate
   ---------               --------              ----
V-1: main: * iteration 1 *
V-2: main (for j loop): making testdir, "/mnt/mdtest/#test-dir.0-0"
V-3: main (create hierarchical directory loop-!collective_creates): Calling create_remove_directory_tree with "/mnt/mdtest/#test-dir.0-0"
V-1: Entering create_remove_directory_tree, currDepth = 0...
V-2: Making directory "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/"
V-1: Entering create_remove_directory_tree, currDepth = 1...
V-2: Making directory "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/"
V-1: Entering create_remove_directory_tree, currDepth = 2...
V-2: Making directory "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/"
V-1: Entering create_remove_directory_tree, currDepth = 2...
V-1: main:   Tree creation     :          0.000 sec,      15345.347 ops/sec
V-3: main: Copied unique_mk_dir, "mdtest_tree.0.0", to topdir
V-1: Entering file_test...
V-1: Entering unique_dir_access...
V-1: Entering offset_timers...
V-3: file_test: create path is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0"
V-1: Entering create_remove_items, currDepth = 0...
V-3: create_remove_items (start): temp_path is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0"
V-1: Entering create_remove_items, currDepth = 1...
V-3: create_remove_items (start): temp_path is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0"
V-3: create_remove_items (for loop): temp_path is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/"
V-1: Entering create_remove_items_helper...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.10"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.11"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.12"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.13"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.14"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.15"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.16"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.17"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.18"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1//file.mdtest.0.19"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-1: Entering create_remove_items, currDepth = 2...
V-3: create_remove_items (start): temp_path is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/"
V-3: create_remove_items (for loop): temp_path is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/"
V-1: Entering create_remove_items_helper...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.20"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.21"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.22"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.23"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.24"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.25"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.26"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.27"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.28"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-3: create_remove_items_helper (non-dirs create): curr_item is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2//file.mdtest.0.29"
V-3: create_remove_items_helper (non-collective, shared): open...
V-3: create_remove_items_helper: close...
V-1: Entering create_remove_items, currDepth = 2...
V-3: create_remove_items (start): temp_path is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/"
V-1: Entering unique_dir_access...
V-1: Entering offset_timers...
V-3: file_test: stat path is "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0"
V-1: Entering mdtest_stat...
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.10
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.11
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.12
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.13
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.14
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.15
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.16
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.17
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.18
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/file.mdtest.0.19
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.20
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.21
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.22
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.23
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.24
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.25
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.26
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.27
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.28
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.2/file.mdtest.0.29
V-3: mdtest_stat file: /mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/mdtest_tree.0.3/file.mdtest.0.30
V-3: Stat'ing file "/mnt/mdtest/#test-dir.0-0/mdtest_tree.0.0/mdtest_tree.0.1/mdtest_tree.0.3/file.mdtest.0.30"
V-1: Entering PrintTimestamp...
11/20/2018 14:23:50: Process 0: FAILED in mdtest_stat, unable to stat file: No such file or directory
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 CREATE FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

obviously file file.mdtest.0.30 was not created previously.

**Comment by JulianKunkel** [comment]
I can confirm the bug. Minimal configuration that produces the error is:
$ mdtest -C -T -F -V=4 -d out -I 1 -z 1 -b 1 -L -u
Will add this now first to the regressio suite

**Comment by JulianKunkel** [comment]
https://github.com/hpc/ior/compare/fix-112 should do.
