### ISSUE TITLE
missing tags for old versions

### ISSUE THREAD

**Issue by adilger** [hpc/ior#114]
I'm not sure if there was something wrong with the old development/release process, but there are no tags in the git repo for old release tags (maybe they were created and not pushed?).  In particular:

    2.10.3 a56d39e6f1cf64baed12c28bb446792ae0d39d20
    2.999.5 f3c0c73dfd10cc5adefe400fac935a9079dc66f5
    3.0.0 e3d1a774faa2109db845df1052444bdb2e177cb8
    3.0.1 ecf2ba5eb7f0086a45dd21ba30c9a08f6aee3230

I don't know if it is possible to make a PR with only tags in it, so this should probably be done by someone who already has commit access.  I verified the above commits match those in the old LLNL IOR repo.

**Comment by glennklockwood** [comment]
Thanks for hunting these down.  I'll re-create these tags and push them up.

**Comment by glennklockwood** [comment]
Tags are back and source distributions have been rebuilt and uploaded.  Thanks again for catching this.
