### ISSUE TITLE
Required newer version of autotools for successful compilation

### ISSUE THREAD

**Issue by gmarkomanolis** [hpc/ior#12]
On a Cray XC-40, the compilation fails with the following:

ote: checking out 'e1968cd4ad50d3d5dee853ae3b1a8724f4f072c7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at e1968cd... Merge pull request #7 from hjelmn/master
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:82: warning: macro `AM_COND_IF' not found in library
configure.ac:93: warning: macro `AM_COND_IF' not found in library
configure.ac:104: warning: macro `AM_COND_IF' not found in library
configure.ac:115: warning: macro `AM_COND_IF' not found in library
configure.ac:126: warning: macro `AM_COND_IF' not found in library
configure.ac:153: warning: macro `AM_COND_IF' not found in library
configure.ac:166: warning: macro `AM_COND_IF' not found in library
configure.ac:5: error: m4_defn: undefined macro: _m4_divert_diversion
configure.ac:5: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

If I execute:

module load autotools/2.69

Then the compilation is successful. Maybe there should be a message that we need a newer version of Autotools to avoid confusing users?

**Comment by glennklockwood** [comment]
George, what's the default version of autoconf on your CLE that generates this error?  I just pushed  b0bffa0 which fixes some of the incompatibilities with older autoconf versions, but I don't think all of the issues are fixed.

**Comment by JulianKunkel** [comment]
Is this issue still valid George, or can we close it?

**Comment by gmarkomanolis** [comment]
Ops, it seems that only now I received a notification about this thread, my apologies. 
Now we have updated to new CLE with new autoconf and I have no issue. On my side, you can close this issue.
