### ISSUE TITLE
README.md refers to non-existent NOTES.txt

### ISSUE THREAD

**Issue by pawsey-kbuckley** [hpc/ior#125]
Just arrived here, having followed this 

https://sourceforge.net/projects/ior-sio/

Sourceforge page's link to the archived project in this:

   NOTE: Future releases are being hosted at https://github.com/chaos/ior

which then pointed me here, and noticed that this Repo's front page's 
(README.md) text says:

  This repo now contains both IOR and mdtest. See also NOTES.txt

but that there doesn't seem to be a NOTES.txt within this Repo ?

Kevin M. Buckley
-- 
Supercomputing Systems Administrator
Pawsey Supercomputing Centre

**Comment by glennklockwood** [comment]
This should be fixed with #153.
