### ISSUE TITLE
mdtest needs a shift

### ISSUE THREAD

**Issue by johnbent** [hpc/ior#129]
IOR allows shifting the ranks to ensure that readers are not reading from client side cache.

mdtest needs to have this shift as well.  And it needs to be configurable for how "far" to shift so that IO500 can use it for all four phases: create, read, stat, delete.  Then IO500 can run it with create/write, then shift it 25% for read, then shift it another 25% for stat, then shift it another 25% for delete.

**Comment by glennklockwood** [comment]
I think this is what `-N x` does, where x is the number of ranks to shift, but I'm not 100% sure it shifts every single possible phase of create/write/stat/read/destroy though.

**Comment by johnbent** [comment]
My bad; thanks Glenn!  I added some debugging output and checked and you're right:

```
/U/j/i/i/b/i/src$ mpirun -np 4 ./mdtest -n 2 -vvvvv -N 1 -w 3 -e 3 | grep '^Rank 1' | grep file
Rank 1 create ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.1.0
Rank 1 write ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.1.0
Rank 1 create ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.1.1
Rank 1 write ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.1.1
Rank 1 stat ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.2.0
Rank 1 stat ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.2.1
Rank 1 read ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.3.0
Rank 1 read ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.3.1
Rank 1 unlink ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.0.0
Rank 1 unlink ./out/#test-dir.0-0/mdtest_tree.0/file.mdtest.0.1
```

Create/write are same rank but the shift changes it for stat, read, and destroy which seems like the appropriate behavior to me.  Now we just need to change io500 to use this flag to pass a value of 25% of the ranks to maximize likelihood that the shift pushes to a different client node.  I'll go ahead and close this issue.
