### ISSUE TITLE
Building with GPFS should have sensible default for finding libraries

### ISSUE THREAD

**Issue by chrissamuel** [hpc/ior#130]
Hi there,

For GPFS (at least under Linux using RPMs) the location of the install is pretty certain to be /usr/lpp/mmfs as the RPMs are not relocatable:
```
# rpm -qia '*gpfs*' | fgrep Relocations 
Relocations : (not relocatable)
Relocations : (not relocatable)
Relocations : (not relocatable)
Relocations : (not relocatable)
Relocations : (not relocatable)
Relocations : (not relocatable)
```
I believe it would make sense that if `--with-gpfs` is given without arguments then configure (on Linux at least, and probably AIX too given that's the origin of `/usr/lpp`) should default to using `/usr/lpp/mmfs` as the location to try and find GPFS libraries.

All the best!
Chris

**Comment by glennklockwood** [comment]
I believe the GPFS library is always symlinked into /usr/lib, e.g.,

    (haswell)glock@cori01:~$ ls -l /usr/lib/libgpfs.so
    lrwxrwxrwx 1 root root 33 Jan  7 15:17 /usr/lib/libgpfs.so -> /usr/lpp/mmfs/lib/i386/libgpfs.so

A bigger problem is that IBM does not ship static versions of this library.  On systems where static compilation is the default (e.g., Crays), autoconf fails because the header exists, but the [static] library does not.

If you can confirm that the symlink into /usr/lib is _not_ a part of the GPFS library RPM though, we can add */usr/lpp* to the autoconf.

**Comment by chrissamuel** [comment]
Ahh the old static library trick. No, I suspect GPFS doesn't ship static libraries (from the docs I've found they refer to `libgpfs.a` for AIX and `libgpfs.so` for Linux).  My understanding is that most distros discourage the use of static libraries these days, mainly because of the issues they cause by embedding bugs into user created binaries that can't be fixed later by a package upgrade.

Whilst the symlinks are not strictly part of the RPM:
```
csamuel@cori02:~> rpm -qf /usr/lib/libgpfs.so
file /usr/lib/libgpfs.so is not owned by any package
```
they are created/removed by the scripts run by the RPM, as can be seen with:
````
rpm -q gpfs.base --scripts
```

So definitely a PEBCAK!  I'm not used to the fact that the default environment on Cori does static linking by default yet.

Much obliged,
Chris
