### ISSUE TITLE
ior/mdtest should include a git hash in their output

### ISSUE THREAD

**Issue by glennklockwood** [hpc/ior#132]
We should bake a git commit hash into every formal build of IOR/mdtest that is reported (probably through a verbose option) to help users determine exactly what version of IOR/mdtest they are using.  This would help simplify debugging issues for users who check out IOR/mdtest directly from the repository rather than download a packaged source distribution.

**Comment by johnbent** [comment]
I would suggest to include it in all output regardless of verbose to make
sure we always knew which version created a particular output.  That would
have helped with this recent situation where some people (including myself)
weren't aware just by looking at output whether it was run before or after
the mdtest/stonewall bug fix.

**Comment by hjelmn** [comment]
Agreed. autogen should do this. That way or is every tarball.

**Comment by JulianKunkel** [comment]
Autogen would be very unreliable as it may be missed when checking out
another version. That seems to be the way using the ident Attribute:
https://git-scm.com/docs/gitattributes


Am Do., 7. Feb. 2019, 20:43 hat Nathan Hjelm <notifications@github.com>
geschrieben:

**Comment by JulianKunkel** [comment]
I believe this is unreliable as people can change the code. Using the info from META as we do right now is better suited as long as we update META more frequently. I close this issue, if someone wants to work on it, please reopen it.
