### ISSUE TITLE
Comma in comments of IOR scripts lead to failure

### ISSUE THREAD

**Issue by blastmaster** [hpc/ior#144]
Hi, 
I've encountered a problem when using commas in comments in IOR scripts passed with the -f option.
It seems when a comma is in a comment leads to a failure and IOR complains about whats after the comma.

E.g. if I start IOR with the following script.

```
IOR Config

IOR START
     api=POSIX                   # use POSIX I/O 
     useO_DIRECT=1               # bypass I/O buffers
     intraTestBarriers=1         # barriers between open, read/write, and close
     numTasks=0                  # 0 means all tasks
     filePerProc=1               # 1 means each proc access a single file
     blockSize=20G               # gigabytes (64 GB) 
     transferSize=2M             # megabytes (2 MB) 
     writeFile=1
     readFile=1
     segmentCount=1              # number of segments in file
     verbose=0                   # lowest level of verbosity
RUN
IOR STOP
```

I get an error like this:
```
Syntax error in configuration options:  read/write
```
If I then delete the first comma after the "open" the error changes to
```
Syntax error in configuration options:  and close
```
If I finally also delete the last comma in the comment the script works well.

**Comment by JulianKunkel** [comment]
I incorporated the fix into the branch for the parsing as it is related. Now comments in lines are ignored; that means  "#" ain't be a valid character for any option value which seems OK to me. Before IOR only ignored lines which start with a comment.

**Comment by glennklockwood** [comment]
@blastmaster Please let us know if this fixes the issue for you and we'll merge it into master.

**Comment by blastmaster** [comment]
The patch seems to fix the issue. Looking forward to see the patch in master. :)
Thank you.
