### ISSUE TITLE
remove hashtags in filename mdtest

### ISSUE THREAD

**Issue by carlilek** [hpc/ior#168]
mdtest creates test directories beginning with a #, which is a semi-illegal character in posix (ie, it works, but it means something else). I ran into this trying to tab complete cd into a #testdir directory with the mind to delete it, and didn't notice that the tab complete failed, and I had cd'd into my home directory (e.g. cd #), which translates out to cd<space> <comment> in bash. And then I proceeded to delete much of my home directory before noticing.

**Comment by JulianKunkel** [comment]
I would be in favor to remove the hash, what do others think?

**Comment by glennklockwood** [comment]
+1.  This has long been a usability issue for the exact reasons @carlilek mentioned.  Let's get rid of it.

**Comment by johnbent** [comment]
+1
