### ISSUE TITLE
IOR fsync() failures should be errors (ERR) and not warnings (EWARN)

### ISSUE THREAD

**Issue by ta129963** [hpc/ior#174]
We encountered an issue when running IOR buffered I/O to a Lustre file system where a Lustre
OST ran out of space, the fsync() call issued after the write phase received a non-zero return status and printed a warning, and IOR continued on to the data verification phase which reported data miscompares due to missing data blocks because of ENOSPC.  In my opinion the fsync() should have caused the IOR job to abort.  IOR job output is attached.

[IOR_job_output.txt](https://github.com/hpc/ior/files/3473594/IOR_job_output.txt)

**Comment by ta129963** [comment]
This particular IOR job was using the -e option to perform an fsync() after POSIX write close and it is this particular fsync() that failed.

$ grep -A 3 "^IOR_Fsync_POSIX" aiori-POSIX.c
IOR_Fsync_POSIX(void * fd, IOR_param_t * param)
{
    if (fsync(*(int *)fd) != 0) WARN("cannot perform fsync on file");
} /* IOR_Fsync_POSIX() */

**Comment by JulianKunkel** [comment]
A while ago we had a discussion about warnings vs. errors, there might be reasons to continue and others to abort. Maybe it would be useful to have a "strict" option (like in GCC) that turns relevant warnings to an error -- thus it guarantees that no unexpected condition happened.

**Comment by ta129963** [comment]
A "strict" option would be good for at least the fsync() calls.  I think in this particular case the buffered writes were asynchronous and the data block allocation didn't occur until the fsync() call, so essentially the write failed but we got a warning instead of an error.
