### ISSUE TITLE
DAOS checks break configure

### ISSUE THREAD

**Issue by adilger** [hpc/ior#197]
With the recently-landed DAOS changes in I'm getting errors during configure:

    ./configure
    :
    checking for gpfs_fcntl.h... no
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... no
    ./configure: line 7090: syntax error near unexpected token `newline'
    ./configure: line 7090: `  yes:no:'

This problem goes away when the CART/DAOS lines are deleted from `configure.ac`. It looks in `configure` like the shell script is being improperly generated (the `)` is replaced by `fi` in the script), but fixing this specific case is not enough to get it working (the generated script is too messy to debug easily):

    # So?  What about this header?
    case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
      yes:no:
    fi
    
        { $as_echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5

Other configure checks are properly implementing the `case` statement:

    # So?  What about this header?
    case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
      yes:no: )
        { $as_echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5

so I suspect it has to do with the following `AS_IF()` condition not being nested inside the `AC_ARG_WITH([cart],` and `AC_ARG_WITH([daos],` as is done for `AC_ARG_WITH([gpfs],` and `AC_ARG_WITH([lustre],`.

This is running with `autoconf-2.63-5.1` and `automake-1.11.1-4`.

**Comment by glennklockwood** [comment]
@mchaarawi can you take a look at this?  CI didn’t catch this, but I’d refer not to increase the minimum requirements (for sh or autoconf) just for the DAOS backend.

**Comment by mchaarawi** [comment]
yes, ill push a patch shortly.

**Comment by mchaarawi** [comment]
@adilger  could you please check with:
https://github.com/hpc/ior/pull/198
i reproduced the issue with your mentioned autotools, and that PR seems to resolve it.
