### ISSUE TITLE
mdtest - self referencing sprintf

### ISSUE THREAD

**Issue by eddiecwc** [hpc/ior#20]
in mdtest.c, sprintf of testdir references itself. When I tried to run this it wipes the original value of testdir completely and the new value of testdir is . followed by value of j.

            strcat(testdir, TEST_DIR);
            sprintf(testdir, "%s.%d", testdir, j);

my undersdtanding is that behavior of self referencing sprintf depends on compiler. In my experiments, when compiled with openmpi based mpicc it works as intended. However with mpich the original value of testdir prior to the sprintf was simply wiped out and the resulting value includes just the . and value of j. I also tried some other simple self referencing sprintfs with different compilers and it does look like behavior is not consistent. For example:

```
#include <limits.h>
#include <stdio.h>

int main(int argc, char **argv) {
    char buf[PATH_MAX] = "/gpfs/path/";
    int i=0;

    sprintf (buf, "path is %s", buf);
    printf ("%s\n", buf);
}
```

on a ppc64le node with rhel7.4 & gcc:
```
# cc test.c
# ./a.out
path is path is pat
```

On my my macbook:
```
$ cc test.c
$ ./a.out
path is path is th/
```

**Comment by glennklockwood** [comment]
Thanks for reporting this.  Indeed, POSIX 1003.1's definition of sprintf says that the behavior of self-referenced sprintf is undefined.  This should be fixed.

**Comment by JulianKunkel** [comment]
I had seen that too and had a fix for it on my branch, have included that in my pull request.
Looking forward that we prepare a (benchmarking) roadmap...

**Comment by JulianKunkel** [comment]
Fixed in testing branch.
