### ISSUE TITLE
IOR and mdtest need mechanisms to prevent compression and dedup

### ISSUE THREAD

**Issue by johnbent** [hpc/ior#203]
Client-side compression and client-side dedup (ala [LBFS](https://pdos.csail.mit.edu/archive/lbfs/) could allow unrealistic rates to be reported.  To prevent compression without adding problematic overhead, we can write random bytes to the buffer before opening the file and before starting any timers.  To prevent dedup without adding problematic overhead, we could modify a byte in the buffer between IOs.  Something like this:
`write random bytes to buffer`
`start timer`
`open file`
`for i = 0 ...`
`  buffer[i%buf_size]++`
`  write buffer`
`close file`
`end timer`

And there should be a shared function used by write/verify that sets the buffer: there should be only one place in the code with the logic for deciding what should be in the buffer (either to write it or to verify it after read).

Probably these should be controlled by a flag like '--random' and there clearly needs to be a '--random-seed S' flag so that the randomization can be shared across asynchronous write/read phases.

**Comment by JulianKunkel** [comment]
The infrastructure had been improved, now mdtest has file-individual signatures. That could be slightly modified to change 4 bytes per page to make it truly look random.

**Comment by JulianKunkel** [comment]
In the meantime, various code has been integrated to provide such buffers.
