### ISSUE TITLE
Opening result file many times

### ISSUE THREAD

**Issue by rldleblanc** [hpc/ior#204]
When specifying `summaryFile` for `ior` and there are more jobs on rank 0, there are a lot of opens and messages. Can this be changed to only happen of the first occurrence?

https://github.com/hpc/ior/blob/3a34b2efb7b0d5faafa0802426907cef3c3f3fc3/src/parse_options.c#L114-L121

**Comment by JulianKunkel** [comment]
In a scriptfile, you can specify for each test a different summaryFile. That is intentional. As only rank 0 manages the output file, there is only one job. I hope that clarifies the matter (otherwise reopen, and clarify the issue).

**Comment by rldleblanc** [comment]
It's been quite a while, so excise me if my memory is a bit rusty. If I can twenty processes on a single node with summary output, all 20 threads would open up the same file and would append or clobber each other causing the output to be invalid. If I remember correctly, they were all trying to write the same data, but it was all messed up. I worked around it by having each thread with their own file and only picking the first one, but it prevented just piping the output to my next process. (I had to save all the files, then read the one and then clean up all the files created).

**Comment by JulianKunkel** [comment]
It shouldn't be that way as you should run not 20 threads but 20 processes
using MPI. On Line 115, there is:
if (rank == 0){ which ensures that only process 0 would do it regardless
how many there are. You may have observed this when the application is
executed with a wrong mpiexec maybe as it then would see 20 independent
programs and all think they are rank 0.
