### ISSUE TITLE
Is there a reason POSIX always opens a file RDWR instead of using openFlags?

### ISSUE THREAD

**Issue by rldleblanc** [hpc/ior#205]
At https://github.com/hpc/ior/blob/3a34b2efb7b0d5faafa0802426907cef3c3f3fc3/src/aiori-POSIX.c#L470 it is using or with RDWR to always open a file read write instead of using the openFlags. Is there a reason for that? Some storage opens files differently if it is just read or if it intends to be appended to. It may also make the case for a separate test that performs an append verses a straight write and straight read test where the files are open with the appropriate flags. It could also help with debugging storage systems.

Thanks

**Comment by JulianKunkel** [comment]
That might have been intentional as, e.g., the HDF5 backend required the usage of RDWR.
With the current version of IOR it isn't needed anymore and IOR uses WRONLY and RDONLY. It is up to the backends to then ensure proper working.
