### ISSUE TITLE
IOR HANGs - in collective-mode

### ISSUE THREAD

**Issue by wszoecs** [hpc/ior#210]
Hi,

we found a quite fundamental bug in ior lately:
if you run IOR in collective-mode (MPIIO or HDF5) - AND - stonewalled, then in the while()-loop in ior.c - it can happen, that SOME ranks set 'hitStonewall' to 1 - while some don't.

The next loop-iteration then will run with not all ranks participating in the collective-op, which will lead to an indefinite HANG!
(yes, this issue also exists and can be triggered in earlier IOR-versions)

The attached patch successfully prevents this case, by sync'ing the 'hitStonewall' status of rank-0 to all other ranks --- but only in those cases, where this 'all or none' behavior is essential.

[ior-collective-patch.txt](https://github.com/hpc/ior/files/3983318/ior-collective-patch.txt)

**Comment by JulianKunkel** [comment]
Good catch.
It does have performance implications though but at the moment, it appears there is no way around.
