### ISSUE TITLE
The option -B is documented, in ior/doc/USER_GUIDE but not implemented?

### ISSUE THREAD

**Issue by novak5-llnl** [hpc/ior#213]
The option is documented as:
 -B    useO_DIRECT -- uses O_DIRECT for POSIX, bypassing I/O buffers
Yet in ior/src/parse_options.c, it is not listed as an option in the option_help
It appears that O_DIRECT may not be implemented?

**Comment by JulianKunkel** [comment]
The option is now integrated into the POSIX backend module,
$ ./src/ior -h 
shows that it is called
--posix.odirect

I fixed the documentation, thanks!
