### ISSUE TITLE
Using latest code for IOR / mdtest I see a crash.

### ISSUE THREAD

**Issue by jasimmons1973** [hpc/ior#218]
When I run the following command I see:

/lustre/crius/stf008/scratch/jsimmons/ppc64le/mdtest '-n' '14285' '-i' '5' '-u' '-d' '/lustre/crius/stf008/scratch/jsimmons/dne2_2_mds_md_test/unique_100k'

Nodemap: 111111111111110000000000000000000000000000000000000000000000000000000000000000000000
84 tasks, 1199940 files/directories
[pike10:07644] *** Process received signal ***
[pike10:07644] Signal: Segmentation fault (11)
[pike10:07644] Signal code: Address not mapped (1)
[pike10:07644] Failing at address: (nil)
[pike10:07644] [ 0] [0x3fffb6720478]
[pike10:07644] [ 1] /lustre/crius/stf008/scratch/jsimmons/ppc64le/mdtest[0x100095cc]
[pike10:07644] [ 2] /lustre/crius/stf008/scratch/jsimmons/ppc64le/mdtest[0x10009d70]
[pike10:07644] [ 3] /lustre/crius/stf008/scratch/jsimmons/ppc64le/mdtest[0x1000a394]
[pike10:07644] [ 4] /lustre/crius/stf008/scratch/jsimmons/ppc64le/mdtest[0x1000b5f8]
[pike10:07644] [ 5] /lustre/crius/stf008/scratch/jsimmons/ppc64le/mdtest[0x1000f748]
[pike10:07644] [ 6] /lustre/crius/stf008/scratch/jsimmons/ppc64le/mdtest[0x1000320c]
[pike10:07644] [ 7] /lib64/libc.so.6(+0x25280)[0x3fffb6295280]
[pike10:07644] [ 8] /lib64/libc.so.6(__libc_start_main+0xc4)[0x3fffb6295474]
[pike10:07644] *** End of error message ***

**Comment by JulianKunkel** [comment]
Can you state how many procs you used and the environment you run this on? Is it powerPC?
I did rerun the command with 5 procs which worked for me on an Ubuntu 18.04/Intel platform. 
Then using valgrind and also recompiled using GCC sanitizer.
$ make CFLAGS="-fsanitize=address -fno-omit-frame-pointer"
and sanitize=undefined
which didn't reveal a memory issue.
Thanks for your help.

**Comment by jasimmons1973** [comment]
Sorry for the delay. I did try this:

/lustre/crius/stf008/scratch/jsimmons/x86_64/mdtest '-n' '28571' '-i' '5' '-u' '-d' '/lustre/crius/stf008/scratch/jsimmons/dne2_4_mds_md_test/unique_100k'

and it failed with:

[ninja60:00545] *** Process received signal ***
[ninja60:00543] *** Process received signal ***
[ninja60:00544] *** Process received signal ***
[ninja60:00546] *** Process received signal ***
[ninja60:00541] *** Process received signal ***
[ninja60:00542] *** Process received signal ***
--------------------------------------------------------------------------
mpirun noticed that process rank 4 with PID 545 on node ninja60 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

I wonder if its the same problem. RHEL7.7 environment with the default OpenMPI stack on x86. The Power8 is also a default RHEL7.7 environment with also the default OpenMPI stack.

**Comment by JulianKunkel** [comment]
Could you try to run it with valgrind:
valgrind /lustre/crius/stf008/scratch/jsimmons/x86_64/mdtest '-n' '28571' '-i' '5' '-u' '-d' '/lustre/crius/stf008/scratch/jsimmons/dne2_4_mds_md_test/unique_100k'

As it worked for me with 5 procs

**Comment by jasimmons1973** [comment]
I see a lot of:

==12737== 656 bytes in 1 blocks are definitely lost in loss record 5,738 of 5,858
==12737==    at 0x4C2BF79: calloc (vg_replace_malloc.c:762)
==12737==    by 0x5405729: ompi_op_base_op_select (in /usr/lib64/openmpi/lib/libmpi.so.12.0.7)
==12737==    by 0x53AD7A8: ompi_op_init (in /usr/lib64/openmpi/lib/libmpi.so.12.0.7)
==12737==    by 0x53B1652: ompi_mpi_init (in /usr/lib64/openmpi/lib/libmpi.so.12.0.7)
==12737==    by 0x53D40C2: PMPI_Init (in /usr/lib64/openmpi/lib/libmpi.so.12.0.7)
==12737==    by 0x402F78: main (mdtest-main.c:5)

**Comment by JulianKunkel** [comment]
These happen typically. Can you send to me by email the whole valgrind output?

**Comment by jasimmons1973** [comment]
send

**Comment by JulianKunkel** [comment]
Based on the email follow up we had, I like to repeat it:
From the Commands it does look correct, however, it appears I only see
MPI_Init errors.

I just rerun the commands successfully on my PC, so that I believe
must be something very strange, from the results-x86, it looks a bit
like compiling with one MPI library header and linking to another or
something like this.

To be sure:
- please clone IOR again and configure it again.

Then check with $ ld mdtest
Which libraries are linked. Does IOR work at all? I suspect the error
appears even when you just call ./mdtest or just call ./ior

If that doesn't fix the issue, set:
$ ulimit -c unlimited
And run again to obtain the core file.

$ gdb -c core
Should then show the line the problem appears but I think it is a
linking issue at the moment.

Maybe I haven't received your respone, if we don't hear from you, it appears we can close this issue.

**Comment by jasimmons1973** [comment]
I like to point out I did a pull today and this issue resolved itself. So this is not a problem with the latest IOR version.
