### ISSUE TITLE
IOR json output mangled

### ISSUE THREAD

**Issue by blepore** [hpc/ior#233]
Hi Folks, 

We picked up master yesterday (6/24/20) and noticed that the json output appears to be missing a closing bracket ']' in the 'Results' section.

You can repro this by running something like this: 
`mpirun --hostfile hosts.txt --map-by node -np 32 /usr/laaso/bin/ior -z -w -r -i 3 -m -d 1 -e -F -o /lustre/ior/test.file_tput_n_to_n.1593037867 -t 32m -b 32m -A 328883 -O summaryFormat=JSON -O summaryFile=/lustre/ioroutput/out.n_to_n_tput.159303786`

Line 156 is empty but should have a ']'

**Comment by glennklockwood** [comment]
Thanks for reporting.  This underscores the need for #202.

**Comment by blepore** [comment]
Wow, that was quick. Great job! Thanks for the help! We'll test it and, if it works, I can come back and close this.
