### ISSUE TITLE
Not able to configure IOR without MPI when configuring with GPFS

### ISSUE THREAD

**Issue by evioxtech** [hpc/ior#239]
Please note that I am not able to compile for without mpiio

[root@hpcinteractive01 ior]# ./configure --without-mpiio --with-gpfs
checking metadata... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for mpicc... no
checking for mpixlc_r... no
checking for mpixlc... no
checking for hcc... no
checking for mpxlc_r... no
checking for mpxlc... no
checking for sxmpicc... no
checking for mpifcc... no
checking for mpgcc... no
checking for mpcc... no
checking for cmpicc... no
checking for cc... cc
checking for gcc... (cached) cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking dependency style of cc... gcc3
checking for function MPI_Init... no
checking for function MPI_Init in -lmpi... no
checking for function MPI_Init in -lmpich... no
configure: error: in `/gpfs/home/tpathare/benchmark/ior':
configure: error: MPI compiler requested, but could not use MPI.
See `config.log' for more details

**Comment by JulianKunkel** [comment]
On my system (no GPFS), it builds correctly without MPIIO in this example.
Does it work without specifying GPFS?
Could you have a look at the last section of config.log?

**Comment by hjelmn** [comment]
It is not looking for MPI-IO. It is looking just looking for MPI. Not sure why that is required for GPFS.

**Comment by hjelmn** [comment]
Doesn't IOR require MPI in all cases. If so this should be closed.

**Comment by JulianKunkel** [comment]
Could you pass along the config.log?

**Comment by JulianKunkel** [comment]
Yes, it does require MPI but you can build without the MPIO module if you
want. Not sure why someone wants that but you can.

**Comment by hjelmn** [comment]
Looking at the output it fails to find ```MPI_Init```. They need to install either Open MPI or MPICH to use IOR.

**Comment by JulianKunkel** [comment]
That would be a simple explanation. I understood the email, that the
compiler misconfigured MPI when running with --without-mpiio.
evioxtech <https://github.com/evioxtech> can you provide additional
information as requested?

**Comment by JulianKunkel** [comment]
As there wasn't any update, I close the issue.
