### ISSUE TITLE
mdtest: stats an unexisting file with stonewalling

### ISSUE THREAD

**Issue by reflectored** [hpc/ior#241]
I run the following command:

> mdtest -d /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/ -V 3 -n 10000 -u -L -P -W 120 -x /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/stonewall

I get the following error:

> 06/22/2020 13:30:54: Process 0: FAILED in mdtest_stat, unable to stat file /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/file.mdtest.0.1: No such file or directory 

The verbose logs do not show that the file, file.mdtest.0.1, in the particular path above has been created:

> V-1: Rank 0 Line 305 Entering unique_dir_access, set it to /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0
> V-1: Rank 0 Line 225 V-1: Entering offset_timers...
> V-3: Rank 0 Line 1048 file_test: create path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0'
> V-1: Rank 0 Line 481 Entering create_remove_items on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0, currDepth = 0...
> V-3: Rank 0 Line 487 create_remove_items (start): temp_path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0'
> V-1: Rank 0 Line 412 Entering create_remove_items_helper on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0
> V-3: Rank 0 Line 356 create_remove_items_helper (non-dirs create): curr_item is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/file.mdtest.0.0'
> V-3: Rank 0 Line 383 create_remove_items_helper (non-collective, shared): open...
> V-1: Rank 1 Line 305 Entering unique_dir_access, set it to /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0
> V-1: Rank 1 Line 225 V-1: Entering offset_timers...
> V-3: Rank 1 Line 1048 file_test: create path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0'
> V-1: Rank 1 Line 481 Entering create_remove_items on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0, currDepth = 0...
> V-3: Rank 1 Line 487 create_remove_items (start): temp_path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0'
> V-1: Rank 1 Line 412 Entering create_remove_items_helper on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0
> V-3: Rank 1 Line 356 create_remove_items_helper (non-dirs create): curr_item is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0/file.mdtest.1.0'
> V-3: Rank 1 Line 383 create_remove_items_helper (non-collective, shared): open...
> V-3: Rank 0 Line 404 create_remove_items_helper: close...
> V-1: Rank 0 Line 998 stonewall hit with 10000 items
> V-3: Rank 1 Line 404 create_remove_items_helper: close...
> V-1: Rank 1 Line 998 stonewall hit with 10000 items
> Continue stonewall hit min: 0 max: 10000 avg: 0.0
> 
> V-1: Rank 1 Line 1065 stonewall: 10000 of 10000
> V-1: Rank 1 Line 481 Entering create_remove_items on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0, currDepth = 0...
> V-3: Rank 1 Line 487 create_remove_items (start): temp_path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0'
> V-1: Rank 1 Line 412 Entering create_remove_items_helper on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0
> V-1: Rank 0 Line 305 Entering unique_dir_access, set it to /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0
> V-1: Rank 0 Line 225 V-1: Entering offset_timers...
> V-1: Rank 1 Line 305 Entering unique_dir_access, set it to /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0
> V-1: Rank 1 Line 225 V-1: Entering offset_timers...
> V-3: Rank 1 Line 1113 file_test: stat path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0'
> V-1: Rank 1 Line 549 Entering mdtest_stat on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0
> V-3: Rank 1 Line 618 mdtest_stat file: /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0/file.mdtest.1.0
> V-3: Rank 0 Line 1113 file_test: stat path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0'
> V-1: Rank 0 Line 549 Entering mdtest_stat on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0
> V-3: Rank 0 Line 618 mdtest_stat file: /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/file.mdtest.0.0
> V-3: Rank 0 Line 618 mdtest_stat file: /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/file.mdtest.0.1
> V-1: Entering PrintTimestamp...
> 06/22/2020 13:30:54: Process 0: FAILED in mdtest_stat, unable to stat file /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/file.mdtest.0.1: No such file or directory

**Comment by JulianKunkel** [comment]
Stonewalling hasn't been completely integrated in all branches of mdtest as
the code is unfortunately not easy to maintain.
In this case, stonewalling working on directories isn't yet implemented
fully.
You call would work if you run only on files (add the -F flag).  Is it very
important for you to be able to test now on directories?

**Comment by reflectored** [comment]
Thank you for the quick response. We are willing to test the metadata performance of our distributed filesystem Quobyte, therefore testing paths that contain directories is important for us. I will give "-F" a try.

**Comment by reflectored** [comment]
I encounter the same problem with "-F":

> mdtest-3.3.0+dev was launched with 2 total task(s) on 2 node(s)
> Command line used: /home/alexey/Quobyte/ior/src/mdtest '-d' '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/' '-V' '3' '-n' '100' '-u' '-L' '-F' '-P' '-W' '120' '-x' '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom//stonewall'
> V-1: Rank   0 Line   239 Entering parse_dirpath on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/...
> V-1: Rank   0 Line  1395 main: Setting create/stat/read/remove_only to True
> V-1: Rank   0 Line  1398 Entering valid_tests...
> V-1: Rank   0 Line  2015 api                     : (null)
> V-1: Rank   0 Line  2016 barriers                : True
> V-1: Rank   0 Line  2017 collective_creates      : False
> V-1: Rank   0 Line  2018 create_only             : True
> V-1: Rank   0 Line  2019 dirpath(s):
> V-1: Rank   0 Line  2021 	/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/
> V-1: Rank   0 Line  2023 dirs_only               : False
> V-1: Rank   0 Line  2024 read_bytes              : 0
> V-1: Rank   0 Line  2025 read_only               : True
> V-1: Rank   0 Line  2026 first                   : 1
> V-1: Rank   0 Line  2027 files_only              : True
> V-1: Rank   0 Line  2031 iterations              : 1
> V-1: Rank   0 Line  2032 items_per_dir           : 0
> V-1: Rank   0 Line  2033 last                    : 0
> V-1: Rank   0 Line  2034 leaf_only               : True
> V-1: Rank   0 Line  2035 items                   : 100
> V-1: Rank   0 Line  2036 nstride                 : 0
> V-1: Rank   0 Line  2037 pre_delay               : 0
> V-1: Rank   0 Line  2038 remove_only             : True
> V-1: Rank   0 Line  2039 random_seed             : 0
> V-1: Rank   0 Line  2040 stride                  : 1
> V-1: Rank   0 Line  2041 shared_file             : False
> V-1: Rank   0 Line  2042 time_unique_dir_overhead: False
> V-1: Rank   0 Line  2043 stone_wall_timer_seconds: 120
> V-1: Rank   0 Line  2044 stat_only               : True
> V-1: Rank   0 Line  2045 unique_dir_per_task     : True
> V-1: Rank   0 Line  2046 write_bytes             : 0
> V-1: Rank   0 Line  2047 sync_file               : False
> V-1: Rank   0 Line  2048 call_sync               : False
> V-1: Rank   0 Line  2049 depth                   : 0
> -- started at 07/20/2020 15:13:34 --
> 
> mdtest-3.3.0+dev was launched with 2 total task(s) on 2 node(s)
> Command line used: /home/alexey/Quobyte/ior/src/mdtest '-d' '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/' '-V' '3' '-n' '100' '-u' '-L' '-F' '-P' '-W' '120' '-x' '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom//stonewall'
> V-1: Rank   1 Line   239 Entering parse_dirpath on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/...
> V-1: Rank   1 Line  1395 main: Setting create/stat/read/remove_only to True
> V-1: Rank   1 Line  1398 Entering valid_tests...
> V-1: Rank   1 Line  2015 api                     : (null)
> V-1: Rank   1 Line  2016 barriers                : True
> V-1: Rank   1 Line  2017 collective_creates      : False
> V-1: Rank   1 Line  2018 create_only             : True
> V-1: Rank   1 Line  2019 dirpath(s):
> V-1: Rank   1 Line  2021 	/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/
> V-1: Rank   1 Line  2023 dirs_only               : False
> V-1: Rank   1 Line  2024 read_bytes              : 0
> V-1: Rank   1 Line  2025 read_only               : True
> V-1: Rank   1 Line  2026 first                   : 1
> V-1: Rank   1 Line  2027 files_only              : True
> V-1: Rank   1 Line  2031 iterations              : 1
> V-1: Rank   1 Line  2032 items_per_dir           : 0
> V-1: Rank   1 Line  2033 last                    : 0
> V-1: Rank   1 Line  2034 leaf_only               : True
> V-1: Rank   1 Line  2035 items                   : 100
> V-1: Rank   0 Line  2050 make_node               : 0
> V-1: Rank   1 Line  2036 nstride                 : 0
> V-1: Rank   1 Line  2037 pre_delay               : 0
> V-1: Rank   1 Line  2038 remove_only             : True
> V-1: Rank   1 Line  2039 random_seed             : 0
> V-1: Rank   1 Line  2040 stride                  : 1
> V-1: Rank   1 Line  2041 shared_file             : False
> V-1: Rank   1 Line  2042 time_unique_dir_overhead: False
> V-1: Rank   1 Line  2043 stone_wall_timer_seconds: 120
> V-1: Rank   1 Line  2044 stat_only               : True
> V-1: Rank   1 Line  2045 unique_dir_per_task     : True
> V-1: Rank   1 Line  2046 write_bytes             : 0
> V-1: Rank   1 Line  2047 sync_file               : False
> V-1: Rank   1 Line  2048 call_sync               : False
> V-1: Rank   1 Line  2049 depth                   : 0
> V-1: Rank   1 Line  2050 make_node               : 0
> V-3: Rank   1 Line  2154 main (before display_freespace): testdirpath is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/'
> V-3: Rank   0 Line  2154 main (before display_freespace): testdirpath is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/'
> V-3: Rank   0 Line  1537 Entering display_freespace on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/...
> V-3: Rank   0 Line  1559 Before show_file_system_size, dirpath is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom'
> V-1: Rank   0 Line  1490 Entering show_file_system_size on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom
> Path: /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom
> FS: 2.3 TiB   Used FS: 0.0%   Inodes: 8796093022208.0 Mi   Used Inodes: 0.0%
> 
> V-3: Rank   0 Line  1561 After show_file_system_size, dirpath is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom'
> 
> Nodemap: 10
> V-3: Rank   0 Line  2169 main (after display_freespace): testdirpath is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/'
> V-3: Rank   1 Line  2169 main (after display_freespace): testdirpath is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/'
> 2 tasks, 200 files
> V-1: Rank   0 Line  2238 
> V-1: Rank   0 Line  2239    Operation               Duration              Rate
> V-1: Rank   0 Line  2240    ---------               --------              ----
> V-1: Rank   0 Line  1648 main: * iteration 1 *
> V-2: Rank   0 Line  1653 main (for j loop): making testdir, '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0'
> V-1: Rank   1 Line  2238 
> V-1: Rank   1 Line  2239    Operation               Duration              Rate
> V-1: Rank   1 Line  2240    ---------               --------              ----
> V-1: Rank   1 Line  1648 main: * iteration 1 *
> V-2: Rank   1 Line  1653 main (for j loop): making testdir, '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0'
> V-3: Rank   0 Line  1696 main (create hierarchical directory loop-!collective_creates): Calling create_remove_directory_tree with '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0'
> V-1: Rank   0 Line  1573 Entering create_remove_directory_tree on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0, currDepth = 0...
> V-2: Rank   0 Line  1579 Making directory '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/'
> V-3: Rank   1 Line  1696 main (create hierarchical directory loop-!collective_creates): Calling create_remove_directory_tree with '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0'
> V-1: Rank   1 Line  1573 Entering create_remove_directory_tree on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0, currDepth = 0...
> V-2: Rank   1 Line  1579 Making directory '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0/'
> error could not create directory '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0/'
> V-1: Rank   1 Line  1573 Entering create_remove_directory_tree on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0/, currDepth = 1...
> V-1: Rank   0 Line  1573 Entering create_remove_directory_tree on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/, currDepth = 1...
> V-1: Rank   0 Line  1722 V-1: main:   Tree creation     :          0.006 sec,        174.655 ops/sec
> V-3: Rank   0 Line  1743 i 2 nstride 0
> V-3: Rank   0 Line  1753 V-3: main: Copied unique_mk_dir, 'mdtest_tree.0.0', to topdir
> V-3: Rank   0 Line  1765 will file_test on mdtest_tree.0.0
> V-3: Rank   0 Line  1026 Entering file_test on mdtest_tree.0.0
> V-1: Rank   1 Line  1722 V-1: main:   Tree creation     :          0.006 sec,        174.594 ops/sec
> V-3: Rank   1 Line  1743 i 2 nstride 0
> V-3: Rank   1 Line  1753 V-3: main: Copied unique_mk_dir, 'mdtest_tree.1.0', to topdir
> V-3: Rank   1 Line  1765 will file_test on mdtest_tree.1.0
> V-3: Rank   1 Line  1026 Entering file_test on mdtest_tree.1.0
> V-1: Rank   0 Line   305 Entering unique_dir_access, set it to /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0
> V-1: Rank   0 Line   225 V-1: Entering offset_timers...
> V-1: Rank   1 Line   305 Entering unique_dir_access, set it to /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0
> V-1: Rank   1 Line   225 V-1: Entering offset_timers...
> V-3: Rank   1 Line  1048 file_test: create path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0'
> V-1: Rank   1 Line   481 Entering create_remove_items on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0, currDepth = 0...
> V-3: Rank   1 Line   487 create_remove_items (start): temp_path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0'
> V-3: Rank   0 Line  1048 file_test: create path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0'
> V-1: Rank   0 Line   481 Entering create_remove_items on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0, currDepth = 0...
> V-3: Rank   0 Line   487 create_remove_items (start): temp_path is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0'
> V-1: Rank   0 Line   412 Entering create_remove_items_helper on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0
> V-3: Rank   0 Line   356 create_remove_items_helper (non-dirs create): curr_item is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/file.mdtest.0.0'
> V-3: Rank   0 Line   383 create_remove_items_helper (non-collective, shared): open...
> V-1: Rank   1 Line   412 Entering create_remove_items_helper on /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0
> V-3: Rank   1 Line   356 create_remove_items_helper (non-dirs create): curr_item is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0/file.mdtest.1.0'
> V-3: Rank   1 Line   383 create_remove_items_helper (non-collective, shared): open...
> ior ERROR: open64("/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.1.0/file.mdtest.1.0", 66, 0664) failed, errno 2, No such file or directory (aiori-POSIX.c:413)
> application called MPI_Abort(MPI_COMM_WORLD, -1) - process 1

**Comment by JulianKunkel** [comment]
Could you try:
$ mdtest -d out -n 10000000  -u -L -F -P -W 1 -x test.file
So one second wallclock too many files locally?
I was wondering if maybe you got a too old version, sometime in 3.3.0+dev,
this bug was fixed.
In case the bug reveals with this attempt, could you checkout master to be
sure we have the same version?
I understand that you like the stonewall for dir testing, that is good to
know and might be a motivation to fix it.

**Comment by reflectored** [comment]
I have tested it with 3.4.0+dev. Running the command you have provided above, with "-F", does not fail on the local filesystem and on our distributed filesystem Quobyte.

I have given the latest master, 3.4.0+dev, a try again and it seems that there is still a race condition between the create and stat phase for the creation with directories. It has failed both on the local filesystem and on Quobyte. The flags are the same as previously:

> -V 3 -n 10000 -u -L -P -W 120

The latest dir created is dir.mdtest.0.7718:

> V-3: Rank   0 Line   319 create_remove_items_helper (dirs create): curr_item is '/home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/dir.mdtest.0.7718'

Whereas, mdtest tries to stat the next dir:

> 07/21/2020 10:22:46: Process 0: FAILED in mdtest_stat, unable to stat directory /home/alexey/mnt/testing/C0/replicated/datafiles_4a_0ttl/mdtest_custom/test-dir.0-0/mdtest_tree.0.0/dir.mdtest.0.7719

**Comment by JulianKunkel** [comment]
Okay, I see. That is then the current (expected) behavior.
I have submitted a patch that fixes the issue to the extent that it
clarifies what will happen.

The stonewall will now *only* apply to the file path and not stop in the
directory creation and count the time properly.
It will always create the full directory tree, though, thus, the example
here:
$ ./src/mdtest -d out -n 150000  -u -L  -P -W 1 -x test.file

Will mean, always create 150k directories, then stonewall the creation of
150k files and stop if that takes longer than 1s.

It leads for me to an expected output:
SUMMARY time: (of 1 iterations)
   Operation                      Max            Min           Mean
 Std Dev
   ---------                      ---            ---           ----
 -------
   Directory creation        :          2.856          2.856          2.856
         0.000
   Directory stat            :          0.218          0.218          0.218
         0.000
   Directory removal         :          1.702          1.702          1.702
         0.000
   File creation             :          1.000          1.000          1.000
         0.000
   File stat                 :          0.168          0.168          0.168
         0.000
   File read                 :          0.303          0.303          0.303
         0.000
   File removal              :          0.699          0.699          0.699
         0.000
   File create (stonewall)   :             NA             NA          1.000
            NA
   Tree creation             :          0.000          0.000          0.000
         0.000
   Tree removal              :          0.062          0.062          0.062
         0.000
-- finished at 07/21/2020 10:28:50 --

That was an easy but partial fix, i.e., stonewall only works for file
creation.
It would be possible to make it work for the disjoint dir creations as well
but that is more work.

For now, I would recommend to split the testing of dirs and files into two
benchmark runs. That way you can use an appropriate n for the dir test (no
stonewall)
and a high n for file creations and employ stonewall.
