### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by johnbent** [hpc/ior#242]
https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by glennklockwood** [comment]
I have no problem with this, and github should set up the appropriate redirect for existing clones with remotes pointing back to `master`.  If nobody objects or otherwise comments before February 1, let's just do this.

**Comment by carlilek** [comment]
Do eeet.

**Comment by glennklockwood** [comment]
This is done.  GitHub has updated all the outstanding references from 'master' to 'main' and the only dangling references lie in individuals' local checkouts.  It doesn't look like Github maintains automatic redirections anymore, so people with checkouts will have to

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
