### ISSUE TITLE
IOR no longer builds on powerpc

### ISSUE THREAD

**Issue by roblatham00** [hpc/ior#245]
a few months ago someone added a call  `__asm__ volatile("rdtscp" : "=a" (a), "=d" (d), "=c" (c));`   which of course is not going to work on Summit or other PPC platforms.

**Comment by hjelmn** [comment]
Yeah. That is no good. Not sure why that is used instead of clock_gettime().

**Comment by JulianKunkel** [comment]
The call had been added to identify which socket on a multi-socket system
the processes are running. I have reversed the compiler check to by default
return a value.
As this is only used for the "dual mount" option, it shouldn't be a big
issue. Let me know if that resolves the issue for PPC.

**Comment by matthewklos1** [comment]
Still seeing issue on PPC, just pulled latest source and tried compiling. 

```
Making all in src
make  all-recursive
Making all in .
  CC       libaiori_a-ior.o
  CC       libaiori_a-mdtest.o
  CC       libaiori_a-utilities.o
/tmp/ccE07u7N.s: Assembler messages:
/tmp/ccE07u7N.s:4961: Error: unrecognized opcode: `rdtscp'
make[3]: *** [libaiori_a-utilities.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by JulianKunkel** [comment]
I added now configure checks to identify which socket ID functions (if at
all) work. Please run ./bootstrap again on the branch to ensure that the
checks are executed.

**Comment by matthewklos1** [comment]
Running on that branch fixed the optcode/socket issue. Thanks!

Worth noting, compiling normally returns a separate error related to checks for GPFS. In order to get the compile to work running ./configure with the `--without-gpfs` option is required. 

```
Making all in src
make  all-recursive
Making all in .
  CC       libaiori_a-ior-output.o
ior-output.c: In function ‘ShowTestStart’:
ior-output.c:375:42: error: ‘IOR_param_t’ has no member named ‘gpfs_hint_access’
     PrintKeyValInt("gpfsHintAccess", test->gpfs_hint_access);
                                          ^
ior-output.c:376:44: error: ‘IOR_param_t’ has no member named ‘gpfs_release_token’
     PrintKeyValInt("gpfsReleaseToken", test->gpfs_release_token);
                                            ^
make[3]: *** [libaiori_a-ior-output.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by glennklockwood** [comment]
@matthewklos1 can you create a new issue for the gpfs one and attach the config.log associated with that error?

`--without-gpfs` was added because libgpfs is not always shipped in both static and dynamic varieties which causes problems in programming environments that assume one or the other.  This may be something new though.

**Comment by matthewklos1** [comment]
@glennklockwood  - New issue created.
