### ISSUE TITLE
IOR Compile Issue - GPFS Libs/Hints

### ISSUE THREAD

**Issue by matthewklos1** [hpc/ior#248]
When compiling IOR on a system (PPC) with GPFS installed (have not tried without) a compiler issue related to gpfs_hint_access and gpfs_release_token is thrown. 

```
[root@localhost ior]# OMPI_CC=gcc make
Making all in src
make  all-recursive
Making all in .
  CC       libaiori_a-ior-output.o
ior-output.c: In function ‘ShowTestStart’:
ior-output.c:375:42: error: ‘IOR_param_t’ has no member named ‘gpfs_hint_access’
     PrintKeyValInt("gpfsHintAccess", test->gpfs_hint_access);
                                          ^
ior-output.c:376:44: error: ‘IOR_param_t’ has no member named ‘gpfs_release_token’
     PrintKeyValInt("gpfsReleaseToken", test->gpfs_release_token);
                                            ^
make[3]: *** [libaiori_a-ior-output.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```
**Note:** This occurs both when explicitly passing the GPFS libs, and when not. 

**Explicit Syntax:** `LD_LIBRARY_PATH=${MPI_ROOT}/lib OMPI_CC=gcc ./configure LIBS=/usr/lpp/mmfs/lib/libgpfs.so`

The only way this doesn't fail is when the `--without-gpfs` flag is added to the `./configure` step. 

`config.log` is attached below. 

[config.log](https://github.com/hpc/ior/files/5017531/config.log)

**Comment by glennklockwood** [comment]
This is happening because `gpfs_hint_access` is not a part of `IOR_param_t` in `ior.h`.  This may have been broken for a few years now but nobody's tested libgpfs support in a long time.  Also, this is not specific to PPC.

Naively fixing the missing attributes results in more errors inside the gpfs-specific calls, e.g.,

```
aiori-POSIX.c(196): error: struct "aiori_xfer_hint_t" has no field "offset"
          take_locks.access.start = hints->offset;
                                           ^

aiori-POSIX.c(221): error: struct "aiori_xfer_hint_t" has no field "offset"
          free_locks.free.start = hints->offset;
                                         ^

aiori-POSIX.c(603): warning #810: conversion from "aiori_mod_opt_t *" to "int" may lose significant bits
                  gpfs_access_end(fd, length, param, access);
                                              ^

aiori-POSIX.c(603): error #140: too many arguments in function call
                  gpfs_access_end(fd, length, param, access);
                                                     ^

compilation aborted for aiori-POSIX.c (code 2)
```

It looks like we need to freshen up gpfs support or disable it outright until it has a new maintainer.

**Comment by JulianKunkel** [comment]
I don't know about the specific of the GPFS/spectrum scale license, does it
allow to share the header file? If so, compilation testing would be much
easier.

**Comment by glennklockwood** [comment]
Yes, I've uploaded the redistributable headers here: https://github.com/glennklockwood/libgpfs-headers

I believe these correspond to Spectrum Scale 4.2, and I'm not sure how much has changed since then.

**Comment by JulianKunkel** [comment]
I used the headers to modify the code, have a look if it *executes* now correctly.

**Comment by IBMkums** [comment]
With this fix, Iam able to successfully configure and build IOR on node with GPFS 5.0.x installed.
