### ISSUE TITLE
IOR '-R' flag increases memory pressures and causes performance impacts

### ISSUE THREAD

**Issue by sihara** [hpc/ior#249]
If -R option in IOR enables, it causes big memory pressures on data verification for read.
Here is a quick profiling result of memory bandwidth during IOR with/without -R flag. It was tested on a Intel client (1 x Gold 5218, 1 x IB-HDR100). And ior reproted 12.5GB/sec in this csae regardless with/without '-R'.
The memory bandwidth standpoint, without '-R' flag, it was 14GB/s Write and 2.8GB/s Read, but with '-R' flag, It consumed 30GB/s Read and 28GB/s Write.

```codes
Without '-R' : mpirun -np 16 ior -r -a POSIX -t 16m --posix.odirect -b 70000m \
-F -i 1 -C -Q 1 -g -G 27 -k -e -o /es400nv/ior_file_easy -O stoneWallingStatusFile=/es400nv/stonewall -D 100
|---------------------------------------|
|--             Socket  0             --|
|---------------------------------------|
|--     Memory Channel Monitoring     --|
|---------------------------------------|
|-- Mem Ch  0: Reads (MB/s):   506.94 --|
|--            Writes(MB/s):  2348.85 --|
|-- Mem Ch  1: Reads (MB/s):   493.25 --|
|--            Writes(MB/s):  2348.26 --|
|-- Mem Ch  2: Reads (MB/s):   514.79 --|
|--            Writes(MB/s):  2348.90 --|
|-- Mem Ch  3: Reads (MB/s):   450.81 --|
|--            Writes(MB/s):  2325.86 --|
|-- Mem Ch  4: Reads (MB/s):   462.17 --|
|--            Writes(MB/s):  2326.62 --|
|-- Mem Ch  5: Reads (MB/s):   444.50 --|
|--            Writes(MB/s):  2325.87 --|
|-- NODE 0 Mem Read (MB/s) :  2872.45 --|
|-- NODE 0 Mem Write(MB/s) : 14024.36 --|
|-- NODE 0 P. Write (T/s):      18751 --|
|-- NODE 0 Memory (MB/s):    16896.81 --|
|---------------------------------------|
|---------------------------------------||---------------------------------------|
|--                 System Read Throughput(MB/s):       2872.45                --|
|--                System Write Throughput(MB/s):      14024.36                --|
|--               System Memory Throughput(MB/s):      16896.81                --|
|---------------------------------------||---------------------------------------|

with -R: mpirun -np 16 ior -r -R -a POSIX -t 16m --posix.odirect -b 70000m -F \
-i 1 -C -Q 1 -g -G 27 -k -e -o /es400nv/ior_file_easy -O stoneWallingStatusFile=/es400nv/stonewall -D 100
|---------------------------------------|
|--             Socket  0             --|
|---------------------------------------|
|--     Memory Channel Monitoring     --|
|---------------------------------------|
|-- Mem Ch  0: Reads (MB/s):  5031.74 --|
|--            Writes(MB/s):  4716.94 --|
|-- Mem Ch  1: Reads (MB/s):  5026.86 --|
|--            Writes(MB/s):  4717.39 --|
|-- Mem Ch  2: Reads (MB/s):  5035.24 --|
|--            Writes(MB/s):  4717.34 --|
|-- Mem Ch  3: Reads (MB/s):  4997.43 --|
|--            Writes(MB/s):  4687.50 --|
|-- Mem Ch  4: Reads (MB/s):  5000.00 --|
|--            Writes(MB/s):  4688.07 --|
|-- Mem Ch  5: Reads (MB/s):  4993.83 --|
|--            Writes(MB/s):  4688.60 --|
|-- NODE 0 Mem Read (MB/s) : 30085.10 --|
|-- NODE 0 Mem Write(MB/s) : 28215.83 --|
|-- NODE 0 P. Write (T/s):      19325 --|
|-- NODE 0 Memory (MB/s):    58300.93 --|
|---------------------------------------|
|---------------------------------------||---------------------------------------|
|--                 System Read Throughput(MB/s):      30085.10                --|
|--                System Write Throughput(MB/s):      28215.83                --|
|--               System Memory Throughput(MB/s):      58300.93                --|
|---------------------------------------||---------------------------------------|
```
If client has much larger memory bandwidth than IO/network bandwidth, -R flag doesn't give performance impact very much. But if client has big IO/network bandwidth and it's able to deliver high ior throughput, -R flag could cause IO performance impact due to lack of memory bandwidth for reading actual data. (according to above test results, there are  additional 3 x memory bandwidth required for Read verification)
It should improve the algorithm in verification process to reduce memory pressures and would be less performance in the end.

**Comment by JulianKunkel** [comment]
At the moment, a buffer is created and filled with the expected data -- this is done only once except if the pattern includes the block offset (not for IO500, e.g. see -l option of IOR). After data is read into another buffer, both buffers are compared.
In that sense, for larger transfer sizes B: B bytes are read, then you should see another 2*B for the verification = 3*B in total.

**Comment by JulianKunkel** [comment]
It turns out that a memset() was integrated to ensure the buffer was overwritten before reading new data into it. This added one more read and write for the memory buffer., e.g. 4B in total for mem reads and 2B for writes with verification instead of 1B for writes (and 0 for mem reads) without verification.

Please try the version in the branch fix-mem that integrates the computation and removes the need for having extra buffers. It does remove some (IMHO unneeded) verbosity in the output of the comparison as well and also with -v -v shows correct comparison to allow to check if verification is actually turned on.

The incompressible buffer comes at some computational expense calling rand_r() twice per byte, should be still faster than comparing memory for most systems.

Before reading data back into a buffer, before there was a costly memset. This is now replaced by inversing the first 8-bytes in the buffer. That means that an implementation that doesn't read any data still is detected but only reports the first 8-bytes to be wrong instead of the whole buffer. I believe this trade-off is acceptable as it reduces the need to overwrite the memory.

**Comment by sihara** [comment]
I did test patch on my test client. Here is test results.
<pre>
# mpirun --allow-run-as-root -np 16 src/ior -r -R -a POSIX -t 16m --posix.odirect -b 70000m \
-F -i 1 -C -Q 1 -g -G 27 -k -e -o /ai400x/ior_file_easy -O stoneWallingStatusFile=/ai400x/stonewall -D 100 
</pre>
without verivation (-R): master (commit: af2429b)
<pre>
|---------------------------------------||---------------------------------------|
|--                 System Read Throughput(MB/s):      16729.23                --|
|--                System Write Throughput(MB/s):      14673.15                --|
|--               System Memory Throughput(MB/s):      31402.38                --|
|---------------------------------------||---------------------------------------|
</pre>

with -R: master (commit: af2429b)
<pre>
|---------------------------------------||---------------------------------------|
|--                 System Read Throughput(MB/s):      37438.33                --|
|--                System Write Throughput(MB/s):      24410.62                --|
|--               System Memory Throughput(MB/s):      61848.95                --|
|---------------------------------------||---------------------------------------|
</pre>

with -R: master (commit: af2429b) + patch https://github.com/hpc/ior/commit/4e95b7080ab0ed29afe7ae3564bee532d3b363a5
<pre>
|---------------------------------------||---------------------------------------|
|--                 System Read Throughput(MB/s):      26238.78                --|
|--                System Write Throughput(MB/s):      13521.63                --|
|--               System Memory Throughput(MB/s):      39760.41                --|
|---------------------------------------||---------------------------------------|
</pre>

I haven't tested on an original client which has big network bandwidth, but at least, a proposal patch demonstrated an big reduction of memory bandwidth on data verification (-R) and didn't see perf regressions on 1xHDR100.
If I can get an chance to access original client, will check if no performance regression is exist.

**Comment by JulianKunkel** [comment]
That's great, it seems to have had the expected impact, I will close this issue here and continue discussion on the pull req.
