### ISSUE TITLE
Missing Symbols when installing with S3 functionality

### ISSUE THREAD

**Issue by MostafaNabi** [hpc/ior#25]
I've been trying to install the S3 tools and am encountering errors when running 'make'
I have installed aws4c and tested it, it works fine.  Running Scientific Linux 7.4.

My current directory looks like this
`ior-tests`
`--aws4c-lanl`
`--ior-master `

openmpi, libcurl, libxml, libcrypto and libssl are all installed in /lib64/
I've ran the configure command as follows

`./configure --with-S3 --with-aws4c=/root/ior_tests/aws4c-lanl/ LDFLAGS="-L/lib64/" CPPFLAGS=-I/usr/include/libxml2`

Which does not throw any errors, however when I run make I get the following output:

``Making all in src
make[1]: Entering directory `/root/ior_tests/ior-master/src'
make  all-am
make[2]: Entering directory `/root/ior_tests/ior-master/src'
mpicc -std=gnu99  -g -O2  -L/root/ior_tests/aws4c-lanl/ -L/lib64/ -o ior ior-ior.o ior-utilities.o ior-parse_options.o ior-aiori.o   ior-aiori-MPIIO.o  ior-aiori-POSIX.o ior-aiori-S3.o    -lcurl -lxml2 -laws4c -laws4c_extra -lm
/usr/bin/ld: /root/ior_tests/aws4c-lanl//libaws4c.a(aws4c.o): undefined reference to symbol 'BIO_free_all@@libcrypto.so.10'
/usr/lib64/libcrypto.so.10: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [ior] Error 1
make[2]: Leaving directory `/root/ior_tests/ior-master/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/ior_tests/ior-master/src'
make: *** [all-recursive] Error 1
``

The lines with the erros seem to be these two:

`/usr/bin/ld: /root/ior_tests/aws4c-lanl//libaws4c.a(aws4c.o): undefined reference to symbol 'BIO_free_all@@libcrypto.so.10'`
`/usr/lib64/libcrypto.so.10: error adding symbols: DSO missing from command line`

I've been stuck on those for a couple days now and any help would be appreciated, I'm also a recent graduate so still new to this.

**Comment by MostafaNabi** [comment]
Fixed by adding calling with:
`make LIBS="-lssl -lcrypto -lm"`

**Comment by glennklockwood** [comment]
Thanks for reporting this.  As far as I know, the S3 interface isn't being maintained, but I am glad it is still possible to compile it.  We should fix the autoconf script so that it pulls in libcrypto when `--with-s3` is specified.

**Comment by glennklockwood** [comment]
@JulianKunkel does your #247 resolve this issue?

**Comment by JulianKunkel** [comment]
I suppose it does. The previous library still needs testing (vendors?) as it isn't fully compatible with MinIO.
