### ISSUE TITLE
-B option was dropped in v3.3

### ISSUE THREAD

**Issue by glennklockwood** [hpc/ior#250]
Commit 07217c9 added backwards compatibility for the `useO_DIRECT` option, but it did not restore the functionality of the `-B` functionality which was refactored into the POSIX AIORI.

Should we restore `-B` for backwards compatibility, or officially drop it from v3.3 an onwards?  This speaks to the larger question of how well we should try to support input arguments across different major/minor/micro releases.  We hit this particular issue because `-B` was a part of a standard acceptance test argument set that no longer works with the latest version of IOR on one of our systems.

**Comment by JulianKunkel** [comment]
I thought we'd accept that the interface changes for a new major release and that this will need of course an improvement in documentation (which isn't yet completed).
I believe it is easy for the users to find the renamed flags than it prevents wrong usage and programming errors. 
Shouldn't use any dropped flags for a while to prevent wrong interpretation, though.

**Comment by glennklockwood** [comment]
Updated 3.3 docs to reflect this change.
