### ISSUE TITLE
libgpfs.so not found

### ISSUE THREAD

**Issue by HenryYihengXu** [hpc/ior#251]
Hello! I'm trying to run ior but got this error:
`./bin/ior: error while loading shared libraries: libgpfs.so: cannot open shared object file: No such file or directory`

The mpi module I'm using is `cray-mpich/7.7.10`, and hdf5 module is `cray-hdf5-parallel/1.10.5.2`.
Do you know where should I find this lib file? Or should I change the configure file or makefile to resolve it? I would really appreciate it!

**Comment by JulianKunkel** [comment]
Hi, just to debug the situation: your CRAY system has a gpfs/spectrum
scale?
If it hasn't you can run configure with the --without-gpfs option.
With GPFS: This linker error may happen as the library isn't found in a
usual place. Can you have a look e.g. using the locate command or find in
/usr to see where libgpfs.so resides?

**Comment by HenryYihengXu** [comment]
--without-gpfs option worked. Thanks a lot!
