### ISSUE TITLE
not compiling on centOS 8 with gnu9

### ISSUE THREAD

**Issue by LordBonkerz** [hpc/ior#252]
make
Making all in src
make  all-recursive
Making all in .
  CC       ior-ior-main.o
  CC       ior-aiori.o
  CC       ior-aiori-DUMMY.o
  CC       ior-aiori-MPIIO.o
  CC       ior-aiori-MMAP.o
  CC       ior-aiori-POSIX.o
  CC       libaiori_a-ior.o
  CC       libaiori_a-mdtest.o
  CC       libaiori_a-utilities.o
In file included from /usr/include/sys/stat.h:446,
                 from utilities.c:36:
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("
   38 | #if __glibc_has_include ("__linux__/stat.h")
      |                         ^
make[3]: *** [Makefile:1003: libaiori_a-utilities.o] Error 1
make[2]: *** [Makefile:2381: all-recursive] Error 1
make[1]: *** [Makefile:702: all] Error 2
make: *** [Makefile:369: all-recursive] Error 1

**Comment by JulianKunkel** [comment]
This error indicates an issue inside the shipped header file not in IOR
directly:
opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-
gnu/9.2.0/include-fixed/bits/statx.h:38:25: error: missing binary operator
before token "("
38 | #if __glibc_has_include ("*linux*/stat.h")

It might be though that IOR should not include the statx.h file but
certainly the header file has an issue. It appears the compiler doesn't
understand that directive. The term fixed in the directory name suggests
that maybe it was manually patched but not completed? Can you check with
another version of gcc/the gcc includes?

**Comment by LordBonkerz** [comment]
I have setup open-HPC that comes with loaded modules in the environment as default loaded with

openmpi4/4.0.3
gnu9/9.2.0


 module avail 

`--------------------------------------------------------------------------------------------------- /opt/ohpc/pub/moduledeps/gnu9-openmpi4 ----------------------------------------------------------------------------------------------------
   adios/1.13.1    dimemas/5.4.1    extrae/3.7.0    imb/2019.6          netcdf-fortran/4.5.2    omb/5.6.2       pnetcdf/1.12.1      py3-scipy/1.3.3    scorep/6.0       tau/2.29
   boost/1.71.0    example2/1.0     geopm/1.1.0     netcdf-cxx/4.3.1    netcdf/4.7.3            phdf5/1.10.6    py3-mpi4py/3.0.3    scalasca/2.5       sionlib/1.7.4

-------------------------------------------------------------------------------------------------------- /opt/ohpc/pub/moduledeps/gnu9 --------------------------------------------------------------------------------------------------------
   R/3.6.3    gsl/2.6    hdf5/1.10.6    likwid/5.0.1    metis/5.1.0    mpich/3.3.2-ofi    mvapich2/2.3.2    openblas/0.3.7    openmpi4/4.0.3 (L)    pdtoolkit/3.25.1    plasma/2.8.0    py3-numpy/1.17.4    scotch/6.0.6    superlu/5.2.1

--------------------------------------------------------------------------------------------------------- /opt/ohpc/admin/modulefiles ---------------------------------------------------------------------------------------------------------
   spack/0.13.4

---------------------------------------------------------------------------------------------------------- /opt/ohpc/pub/modulefiles ----------------------------------------------------------------------------------------------------------
   EasyBuild/4.2.0        bcbio-nextgen/1.2.3    charliecloud/0.15    example1/1.0        hwloc/2.1.0             miniconda3/py38_4.8.3        os            pmix/3.1.4        singularity/3.4.2    snakemake/5.22.1        valgrind/3.15.0
   autotools       (L)    bowtie/1.3.0           cmake/3.16.2         gnu9/9.2.0   (L)    libfabric/1.10.1 (L)    ohpc                  (L)    papi/5.7.0    prun/2.0   (L)    slurm-drmaa/1.0.7    ucx/1.8.0        (L)

  Where:
   L:  Module is loaded
`
But when I unload gcc9 i loose the mpi libs as this is a module dep for openmpi. grr.

Anyway, thanks for the tip, I had to reorg my $PATH so I hit : gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC) instead of ohpc's gcc9.

and it worked!

Do you think there is something wrong with the GCC version from OHPC that's missing?

Because I have had other issues with compiling in general! :)

Cheers!

**Comment by JulianKunkel** [comment]
That is good news.
I believe the header file is somehow broken (as suggested by the compiler),
maybe that can be seen in other compilation attempts as well?

I believe you can create a simple test for the issue:
In file included from /usr/include/sys/stat.h:446
/opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h:38:25:
error: missing binary operator before token "("
38 | #if __glibc_has_include ("*linux*/stat.h")

as follows, e.g. create test.c:
#include <sys/stat.h>

int main(){
}

Compiling with gcc 9.2 should produce already the error. If not, feel free
to send me the statx.h file and I can check

**Comment by LordBonkerz** [comment]
gcc test.c

No problem!

Created the a.out binary.

here's the contents of  /opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h
/*  DO NOT EDIT THIS FILE.

    It has been auto-edited by fixincludes from:

	"/usr/include/bits/statx.h"

    This had to be done to correct non-standard usages in the
    original, manufacturer supplied header file.  */

/* statx-related definitions and declarations.  Linux version.
   Copyright (C) 2018-2019 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

/* This interface is based on <linux/stat.h> in Linux.  */

#ifndef _SYS_STAT_H
# error Never include <bits/statx.h> directly, include <sys/stat.h> instead.
#endif

/* Use the Linux kernel header if available.  */

/* Use "" to work around incorrect macro expansion of the
   __has_include argument (GCC PR 80005).  */
#if __glibc_has_include ("__linux__/stat.h")
# include "linux/stat.h"
# ifdef STATX_TYPE
#  define __statx_timestamp_defined 1
#  define __statx_defined 1
# endif
#endif

#include <bits/statx-generic.h>

**Comment by LordBonkerz** [comment]
Any the wiser? :) 

Cheers,

John

**Comment by glennklockwood** [comment]
This really sounds like a gcc9/easybuild problem so I don't think it's high up our priority list to debug at the moment.  Sorry!

**Comment by LordBonkerz** [comment]
thanks anyway!

Simply removing the /opt/ohpc/pub/compiler/gcc/9.2.0/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include-fixed/bits/statx.h worked
