### ISSUE TITLE
File layout when using "-z" (random offset)

### ISSUE THREAD

**Issue by bolausson** [hpc/ior#259]
Hello,

I am wondering about the exact file layout when using random offsets (-z).

An example for sequential IO is given in the manual (https://ior.readthedocs.io/en/latest/userDoc/tutorial.html):
![image](https://user-images.githubusercontent.com/10600678/95202086-241f5000-07e1-11eb-8af1-e399b641796c.png)

Could someone provide an example when using "-z"?
Is the random offset happening within a block for a rank or will each I/0 of a rank be randomly spread across an entire segment?

Cheers,
Bjoern

**Comment by JulianKunkel** [comment]
Hi Bjoern,
With -z, first the number N of accesses when using transferSize is
determined (let's call one position where it operates an offset).
Then, each offset is randomly assigned to one process => this may lead to a
slightly unbalanced situation.
Last, the access order of the offsets is shuffled N times.

There is no notion of segments and blocks anymore, they are only needed to
compute the total filesize which is blocksize * segment count.

The respective code is found here:
https://github.com/hpc/ior/blob/master/src/ior.c#L1705

Agreeably the way the code works isn't really efficient, the result isn't
perfectly random nor does it balance the workload.
There had been a discussion to change the random behavior which maybe we
should reopen.

**Comment by bolausson** [comment]
Hello Julian,

I see, thanks for the explanation.

Taking the example from above, would this be a correct interpretation of how a single shared file would look like (although the below image assumes the offsets have been assigned perfectly balanced, which I understood might not be the case)
![image](https://user-images.githubusercontent.com/10600678/95215453-44efa180-07f1-11eb-9c28-94ec7de5cf9c.png)

Greetings,
Bjoern

**Comment by JulianKunkel** [comment]
That looks really great! Would be terrific to have the explanation in the
docs.
Just to be sure: the order in which the assigned offsets are accessed by a
rank is random.

**Comment by bolausson** [comment]
Feel free to use the picture and add it with your explanation to the doc.

To make it more clear that it is random, I renumbered the ranks:
![image](https://user-images.githubusercontent.com/10600678/95217773-deb84e00-07f3-11eb-8498-460818252ac5.png)

Attached the PPTX - fee free to modify.
[IOR-SSF-random.pptx](https://github.com/hpc/ior/files/5334651/IOR-SSF-random.pptx)

Cheers,
Bjoern

**Comment by JulianKunkel** [comment]
This is now the new behavior for random in PR #270 
[](![image](https://user-images.githubusercontent.com/5074634/100127254-d507aa00-2e76-11eb-89a4-d082997888e3.png))
