### ISSUE TITLE
autoconf for S3 support should pull in libcrypto

### ISSUE THREAD

**Issue by glennklockwood** [hpc/ior#26]
See #25 

Configuring with s3 support doesn't automatically pull in libcrypto, causing the subsequent build to break unless `LDFLAGS="-lssl -lcrypto -lm"` is explicitly passed into make.

**Comment by JulianKunkel** [comment]
Is here anyone who builds S3 regularly? If I knew what setting you guys use, I could add it to the docker test harness. I would use minio at the moment...
