### ISSUE TITLE
mdtest --help causes segfault

### ISSUE THREAD

**Issue by rfmohr** [hpc/ior#280]
I compiled mdtest-3.2.1 (configured with the --with-lustre option).  It appears to run fine when running the benchmark tests, but if I run "mdtest --help" I get a segfault error.  I was also able to reproduce this with the current master.

**Comment by JulianKunkel** [comment]
I tried on my system but couldn't reproduce the situation with the current
master.
Could you run $ valgrind mdtest --help
Thanks!

**Comment by rfmohr** [comment]
Looks like my problem was the result of attempting to run the program outside the scope of mpirun (so MPI_Init was failing).  If I run "mpirun mdtest --help", I see the help message but I also get an error message that is likely caused by the program exiting before MPI_Finalize is called.

Would it make more sense to move the logic for processing options before the MPI_Init call?  Then someone could run "mdtest --help" without needing to use mpirun.

**Comment by JulianKunkel** [comment]
That somewhat was a chicken and egg problem. AFAIK, the proper option
output and parsing requires MPI rank to be set.
What would make sense would be to output a better error msg in this
case. My MPI's that I test don't have any problem without using MPI
exec/run, so maybe you could add/test the check?

**Comment by JulianKunkel** [comment]
Due to the discussion, I reckon this issue is resolved.
