### ISSUE TITLE
mdtest - division by zero with MPIIO

### ISSUE THREAD

**Issue by ahueck** [hpc/ior#30]
Running mdtest with the option **-a MPIIO** causes a divide by zero error, e.g., the following log file:
[log.txt](https://github.com/IOR-LANL/ior/files/1661218/log.txt)

Looking at the approximate source of the problem, it seems to come from https://github.com/IOR-LANL/ior/blob/e6e0527d72face86a043b2b59cb87b066c44707b/src/aiori-MPIIO.c#L72

More specifically, my assumption is the **transferSize** member of **IOR_param_t param** may never be correctly initialized (I couldn't find it), causing the divide by zero:
https://github.com/IOR-LANL/ior/blob/e6e0527d72face86a043b2b59cb87b066c44707b/src/aiori-MPIIO.c#L77

Setting **transferSize** in *main(...)* to 1 helps with this specific error, but causes some subsequent error.

Am I using mdtest incorrectly?

**Comment by glennklockwood** [comment]
You are not using mdtest incorrectly--I think you are just the first person to test these new non-POSIX capabilities of mdtest.  It sounds like they aren't working too well.

Setting `param->transferSize = 1` should have no effect when running mdtest, so the fact that it's hitting another error once you do this suggests that the MPI-IO aiori simply doesn't work with mdtest right now.  We need to fix this, and I suspect it'll be a matter of just stubbing off the bits of code that are only relevant to IOR but are causing undefined behavior in mdtest.

**Comment by JulianKunkel** [comment]
Added a check to MDtest to prevent users using others than POSIX.
https://github.com/hpc/ior/commit/e10bebe653bae02ca466da9072b6e7025b61124f
