### ISSUE TITLE
mdtest reports incorrect results in the summary

### ISSUE THREAD

**Issue by sihara** [hpc/ior#300]
While I was running mdtest (master branch: 3e4a0f6) on 40 clients with 640 processes and giving the following options to mdtest.
`ior.git/src/mdtest -i 3 -p 10 -n 2000 -vv -d' //ai400x/mdtest.out`

Because of verbose' option enabled, mdtest printed each results in each iterations below.
<pre>
# grep 'Directory creation:' mdtest-shared-2.12.6_ddn3-40n640p-6781.log 
V-1: Rank   0 Line  1013    Directory creation:         33.598 sec,      38097.012 ops/sec
V-1: Rank   0 Line  1013    Directory creation:         34.177 sec,      37452.405 ops/sec
V-1: Rank   0 Line  1013    Directory creation:         34.493 sec,      37108.799 ops/sec
</pre>

However, in the summary, it reported '156998.399' as a Max value which never reported above.

<pre>
SUMMARY rate: (of 3 iterations)
   Operation                      Max            Min           Mean        Std Dev
   ---------                      ---            ---           ----        -------
   Directory creation        :     156998.399      37108.765      45545.372      29789.602
   Directory stat            :     139699.715     135877.037     138013.779       1592.628
   Directory removal         :      65361.170      64737.446      65019.773        257.975
   File creation             :      73808.240      50352.066      59080.743       8831.481
   File stat                 :     229597.932     225305.353     226776.503       1995.544
   File read                 :      97599.700      95619.056      96877.612        893.088
   File removal              :      68525.670      67407.677      67796.763        515.751
   Tree creation             :       4164.376       3029.394       3764.369        520.383
   Tree removal              :         29.732         28.804         29.321          0.386
V-1: Entering PrintTimestamp...
</pre>
This incorrect reporting didn't happen all time, but it happened sometimes. 
I've tested mdtest 3.3, but it was same incorrect reporting.

**Comment by JulianKunkel** [comment]
The way the reporting works is that the min/max across all process is taken, not about the min/max of an iteration (which would be the mean across the procs during an iteration).
To ensure that this isn't any bug and see the actual numbers, with the current version, you can add as argument:
--print-all-procs
To retrieve the individual process values! I think it is alright.

**Comment by sihara** [comment]
okey, how is it able to print previous summary (max/min of iteration), then?

**Comment by JulianKunkel** [comment]
Not sure if I understand correctly, therefore, here an excerpt of the outputs with a bit description:

$ mpiexec -np 2 ./src/mdtest -v -i 3  -n 100 --print-all-procs

# Here is the performance output of Rank 0 only:
V-1: Rank   0 Line  1013    Directory creation:          0.011 sec,      18777.322 ops/sec
V-1: Rank   0 Line  1013    Directory creation:          0.005 sec,      42965.994 ops/sec
V-1: Rank   0 Line  1013    Directory creation:          0.003 sec,      67687.919 ops/sec

Per process result (rate): # Here rank 0, then followed by rank 1 results:
iteration: 0
Test Directory creation        : 1.877732e+04,1.877318e+04
iteration: 1
Test Directory creation        : 4.296599e+04,4.294996e+04
iteration: 2
Test Directory creation        : 6.768792e+04,6.769074e+04

SUMMARY rate: (of 3 iterations)  # Computing the max/min/mean across all ranks and iterations.
   Operation                      Max            Min           Mean        Std Dev
   ---------                      ---            ---           ----        -------
   Directory creation        :      67690.737      18773.184      43140.852      19969.507

**Comment by sihara** [comment]
I understand changes, but what I was saying, was
<pre>
# grep 'Directory creation:' mdtest-shared-2.12.6_ddn3-40n640p-6781.log 
V-1: Rank   0 Line  1013    Directory creation:         33.598 sec,      38097.012 ops/sec
V-1: Rank   0 Line  1013    Directory creation:         34.177 sec,      37452.405 ops/sec
V-1: Rank   0 Line  1013    Directory creation:         34.493 sec,      37108.799 ops/sec
</pre>
I think those numbers are calculated by the following an formula 
proc x n files / elapsed time (each iteration)

If I assume each results are Ri1, Ri2, Ri3, Max(Ri1, Ri2, Ri3) used to be prevous outout that I wanted to have.

**Comment by JulianKunkel** [comment]
You are correct:
the calculation of rate you see here is pretty much: o.items*size/(t[1] - t[0]) where t[1] and t[0] stems from Rank 0. The output is for rank 0 only and does not include any timing information about any other process -- it does implicit if barriers between phases are used. To get the actual values for all processes and each iteration independently, you need to use --print-all-procs

**Comment by JulianKunkel** [comment]
I've implemented the calculation per iteration (check the commit description). The results are different than using individual ranks. Example for 10 procs, ./src/mdtest -v -i 3  -n 10 below.
I'd appreciate if someone double checks that it does what it should do to prevent mistakes. Therefore, use the --print-all-procs option.

SUMMARY rate: (of 3 iterations)
   Operation         per Rank:      Max            Min           Mean          Std Dev     per Iteration: Max            Min           Mean
   ---------                        ---            ---           ----          -------                    ---            ---           ----
   Directory creation        :     133349.335      15240.973      63062.865      35579.914          45577.003      15240.973      34399.616
   Directory stat            :    2229455.567      21594.583     447946.708     598405.446         256368.843      21594.583     112495.166
   Directory removal         :     157628.759      10529.651      77351.948      42982.214          62096.451      10529.651      37367.989
   File creation             :     301409.087      61433.665     125683.173      64712.016         104202.595      61433.665      84093.570
   File stat                 :    3043769.404     287525.698     542738.382     518464.493         341047.835     287525.698     315202.706
   File read                 :    1538769.292     201977.766     536086.517     336569.589         243124.441     201977.766     227601.180
   File removal              :     591603.957      62083.382     210138.004     125464.295         184991.971      62083.382     131374.599
   Tree creation             :       7351.860       4411.369       5766.245       1211.487           7351.860       4411.369       5766.245
   Tree removal              :       5227.938       3721.609       4284.564        671.216           5227.938       3721.609       4284.564
