### ISSUE TITLE
benchmark renaming and deletion of deep trees

### ISSUE THREAD

**Issue by butonic** [hpc/ior#306]
I stumbled over mbtest when checking https://github.com/juicedata/juicefs. The tests caught my eye because they lack benchmarks for renaming a folder with a large amount of children, aka. a large tree. juicefs, seaweedfs and other solutiongs are using a kv store to implement a filesystem. Depending on the tree implementation you have to make tradeoffs in performance. One example is storing the full path in key: renaming the top folder will cause O(n) key updates, where n is the number of children. Another one is the deleteion of a large tree, which again may lead to O(n) deletes.

I am proposing this here, because mtest seems to be the proper place. Let me know what you think.

**Comment by JulianKunkel** [comment]
I think this is an interesting consideration, rename is in fact not well represented in either benchmark in the repository. It will take time to integrate such a test, working toward a publication would be great.

**Comment by adilger** [comment]
It would seem possible to have an optional rename stage for the output directories between the create and stat, then use the new directory name for the stat and unlink stage. For many systems this would be very fast and not affect stat or unlink performance, but it seems that some will have slowdowns for the rename, and possibly also affect the later stages.

It would be good to rename all of the directories in parallel (for test configurations that have eg. one directory per thread) to measure the rate at which directories can be renamed, reporting the rate fir the rename itself as well as the rate taking the number of entries in each subdirectory into account.

**Comment by JulianKunkel** [comment]
The patch series in #311 doesn't yet resolve the matter but it is providing a foundation to implement renaming of a deep tree and implements a test for the renaming of directory entries (these are empty directories though as this is the standard for mdtest). 

I don't think it is that simple to reuse the pattern to do something meaningful.
Consider the tree created by the following patterns:
$ mpiexec -np 2 ./src/mdtest -n 10 -b 1 -z 2 -C
```
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.0
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.2
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.1
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.1
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.2
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.0
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/dir.mdtest.0.5
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/file.mdtest.1.5
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/dir.mdtest.1.4
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/file.mdtest.0.5
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/dir.mdtest.0.3
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/file.mdtest.1.4
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/dir.mdtest.1.6
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/file.mdtest.1.8
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/dir.mdtest.1.8
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/file.mdtest.1.7
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/file.mdtest.0.8
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/dir.mdtest.1.7
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/dir.mdtest.0.6
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/dir.mdtest.0.7
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/file.mdtest.1.6
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/file.mdtest.0.7
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/dir.mdtest.0.8
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/mdtest_tree.2/file.mdtest.0.6
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/file.mdtest.0.3
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/dir.mdtest.0.4
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/dir.mdtest.1.3
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/file.mdtest.1.3
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/dir.mdtest.1.5
out/test-dir.0-0/mdtest_tree.0/mdtest_tree.1/file.mdtest.0.4
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.1
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.2
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.2
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.0
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.1
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.0
```
$ mpiexec -np 2 ./src/mdtest -n 10  -C
```
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.6
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.5
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.5
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.4
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.9
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.5
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.3
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.0
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.2
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.1
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.8
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.1
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.4
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.2
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.8
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.7
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.8
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.0
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.7
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.6
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.3
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.9
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.4
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.1
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.3
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.2
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.7
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.2
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.3
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.0
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.6
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.5
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.7
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.0.8
out/test-dir.0-0/mdtest_tree.0/dir.mdtest.1.1
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.4
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.6
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.0
out/test-dir.0-0/mdtest_tree.0/file.mdtest.1.9
out/test-dir.0-0/mdtest_tree.0/file.mdtest.0.9
```

**Comment by adilger** [comment]
What about a two-phase parallel rename test?  First name all of the directories `dir.N` to `dir.N.rename` (or similar), which should not conflict with any existing name, then in the second phase, rename all of the `dir.N.rename` directories to `dir.((N+1) % num_dirs` which should also not conflict.  The rename rate would be `2 x num_dirs / (time_phase1 + time_phase2)`.  The reason for separate timings of the two phases is because there would have to be a barrier between them to avoid conflicting rename processes, so it would be more like the average of two iterations, but the actual renames could still happen in parallel.

Having two rename stages allows it to be _optionally_ executed after create and before delete without affecting the state of the system, so whether it is run or not the delete phase would still see the same directory layout, or the rename phase could be run repeatedly on the same filesystem.

Coincidentally we also encountered a user application that was doing a *lot* of renames in a filesystem that caused performance problems, and I made a prototype patch to implement parallel file (and later directory) rename in Lustre for this issue: https://jira.whamcloud.com/browse/LU-12125

**Comment by JulianKunkel** [comment]
Yes, that is kind of the two-phase approach that I mention above.
The key question is to which directories, as this benchmark is meaningful only for deeper trees.
$ mpiexec -np 2 ./src/mdtest -n 10
Has for example only the hierarchy out/test-dir.0-0/mdtest_tree.0
Indeed one process could rename many times test-dir.0-0 ...

**Comment by JulianKunkel** [comment]
@butonic What do you think, would it be OK to measure performance by moving the root-level directories?

**Comment by JulianKunkel** [comment]
Will close this issue now for house keeping. While not perfectly resolved, there exists a benchmark.

**Comment by butonic** [comment]
@JulianKunkel yes renaming root-level directories is a great case! Thx for picking this up!
