### ISSUE TITLE
make aiori-POSIX.c not require #define __USE_GNU

### ISSUE THREAD

**Issue by ezickler** [hpc/ior#32]
I had problems using the O_DIRECT. Got always the warning "cannot use O_DIRECT". Found that 'set_o_direct_flag()' were moved to utilities.c some time but '#define  _GNU_SOURCE' were missing here. Made a fix and a pull request here #31. 
In  aiori-POSIX.c there is still the old code which i dosn't want to delete as i don't know if it affects anything else. But i also think this part needs some work as ' __USE_GNU' is for glibcs internal use only and shouldn't be used.  
https://github.com/IOR-LANL/ior/blob/0e7f48d649864b969c7df1916b70910c15f542ec/src/aiori-POSIX.c#L22-L27

**Comment by glennklockwood** [comment]
This is a good catch and a rather nasty issue.  Thanks for fix to get `O_DIRECT` working.  We'll track the matter of doing `#define __USE_GNU` here.

**Comment by NicoMittenzwey** [comment]
While the fix was merged in January, the current master and official release 3.1.0 are missing it again. They are printing "ior WARNING: cannot use O_DIRECT." and continue without bypassing I/O buffers. I was searching for problems with my hardware / software setup before coming here. 

The fix was removed from src/utilities.c by https://github.com/hpc/ior/commit/a6bfa0f94bb6c51e690375218f9c8481afccd4f9#diff-febcef765c9479da8184b3c1e0f15b6a

**Comment by JulianKunkel** [comment]
Thanks,
that was indeed an unwanted regression.
Now pushed the previous commit again.
Am Di., 18. Sep. 2018 um 16:12 Uhr schrieb Nico Mittenzwey
<notifications@github.com>:
>
> While the fix was merged in January, the current master and official release 3.1.0 are missing it again. They are printing "ior WARNING: cannot use O_DIRECT." and continue without bypassing I/O buffers. I was searching for problems with my hardware / software setup before coming here.
>
> The fix was removed from src/utilities.c by a6bfa0f#diff-febcef765c9479da8184b3c1e0f15b6a
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Dr. Julian Kunkel
Lecturer, Department of Computer Science
+44 (0) 118 378 8218
http://www.cs.reading.ac.uk/
https://hps.vi4io.org/
