### ISSUE TITLE
numTasks potential bug

### ISSUE THREAD

**Issue by wadudmiah** [hpc/ior#329]
In the IOR documentation, it says:

```
numTasks - number of tasks that should participate in the test [0] NOTE: **0 denotes all tasks**
```

But when I set `numTasks` to `0`, I get the following runtime error:

```
ior ERROR: too few tasks for testing, errno 12, Cannot allocate memory (ior.c:1573)
```

The source has the following line that produces this error:

```
if (test->numTasks <= 0)
                ERR("too few tasks for testing");
```

If I'm not mistaken, isn't this a bug?

**Comment by JulianKunkel** [comment]
It seems this is a bug: Updating documentation isn't a strongsuit, yet but work in progress.

**Comment by wadudmiah** [comment]
So I presume `numTasks` should be equal to or less than the number of MPI processes (as in `mpirun -n <procs>`)?

**Comment by JulianKunkel** [comment]
At the moment, yes. It seems sensible to set 0 to be <procs> as you state (this is the size in the MPI communicator)

**Comment by wadudmiah** [comment]
Hi Julian, I didn't realise you were based in Reading. I'm just up the road in Didcot!

**Comment by JulianKunkel** [comment]
It appears that if you set it to -1, then it uses numTasks. I added PR #330 to fix it.  Cool. Let me know if you have any other questions.
