### ISSUE TITLE
size of testFile for shared file

### ISSUE THREAD

**Issue by wadudmiah** [hpc/ior#331]
I ran IOR with 26 and 32 processors which ran fine for a shared file using MPI-IO. When I try to run it with 64 processes (using the same configuration file), it says that I have ran out of disk space. My understanding was that the size of the file will remain constant regardless of the size of MPI_COMM_WORLD (using a shared file)? If this is not the case, how do I calculate the size of the file? 

Thanks in advance.

**Comment by JulianKunkel** [comment]
The size of the overall size is NProc x Block size x Segments.
Btw. if you join the VI4IO slack, there is an IOR channel: https://www.vi4io.org/contribute/start

**Comment by wadudmiah** [comment]
Hi Julian, thanks for the quick reply. The Slack joining link says it has expired.
