### ISSUE TITLE
Strange read scaling bandwidth

### ISSUE THREAD

**Issue by wadudmiah** [hpc/ior#332]
Apologies for the flurry of tickets. I am getting some strange read bandwidth values that I can't make sense of. Below is the bandwidth I am getting with increasing MPI ranks with 16 MPI ranks on a single node:

MPI ranks 2 | 4 | 8 | 16 (1 node) | 32 (2 nodes) | 64 (4 nodes)
MiB BW 11701 | 9021 | 6707 | 6812 | 10912 | 4521

How can the read bandwidth go from the highest value at 2 ranks, go down, then go up at 2 nodes and then go down again at 4 nodes? There is no file lock contention involved since it's only reading a shared file. Thanks in advance.

**Comment by JulianKunkel** [comment]
It is a good idea to post the whole command used (together with the number of nodes and system details), even better to discuss this interactively (you are actually member of the Slack as I saw). 
There are many possible reasons, to get a hunch, one needs more detail as this depends on the system configuration, for instance, number of GPFS servers, network interconnect, used storage media, concurrent usage by other users.
