### ISSUE TITLE
What's the deal with strided accesses?

### ISSUE THREAD

**Issue by roblatham00** [hpc/ior#340]
A decade ago, one could ask IOR to generate a noncontiguous (strided) access.  Today, that is not possible (  https://github.com/hpc/ior/blob/main/src/aiori-MPIIO.c#L123 ).   What happened?

**Comment by adilger** [comment]
That definitely still works for POSIX (IO500 ior-hard is using strided mode), but I guess MPIIO doesn't work?  This would definitely make sense for testing e.g. collective IO handling if IOR is generating strided IOs and MPIIO/ADIO is aggregating them internally for submission to the storage system.

**Comment by roblatham00** [comment]
In general one has to be a little sophisticated to trigger MPI-IO collectives -- if ROMIO sees that the datatype the N processes are using is contiguous anyway, it short circuts and goes to indepenent (unless, as on BlueGene, the `romio_cb_{write,read}` hints are `enable` and not the default `automatic`).    So you cannot just do a "MPI_Type_create_subarray" of a 1-d array and give the first 1 MB to rank 0, 2nd MB to rank 1 ...

In IOR terms, that is using collective, a file view , and multiple segments.
