### ISSUE TITLE
IOR assumes a POSIX backend when removing files

### ISSUE THREAD

**Issue by shanedsnyder** [hpc/ior#35]
IOR calls `access()` to check a file's existence prior to calling into the backend to delete the file. This is unnecessary as the actual `unlink()` (or whatever the underlying call is) can often tell you this itself. At the very least, the `access()` call could be moved into backends that operate on POSIX file systems. Other backends will have their own mechanisms for verifying existence before removal, if needed.

**Comment by JulianKunkel** [comment]
I believe this issue had been fixed with the refactoring.
