### ISSUE TITLE
IOR write verification shows a warning message

### ISSUE THREAD

**Issue by berserk-fury** [hpc/ior#354]
Starting on a436395 the following warning message appears while using the `-W` flag.
`WARNING: Incorrect data on write`

This behavior is still present in the current main tip e8409ed

Reproduction steps (toy example):
`$ ior  -t 1M -b 100M -s 1 -i 1  -C -e -w -W -r -R -g -G 27 -k -d 5 
 -o $(pwd)/testFile -v`
Output: [ior_output_e8409ed.txt](https://github.com/hpc/ior/files/6222996/ior_output_e8409ed.txt)

Last known working commit: 3be3cfb

**Comment by JulianKunkel** [comment]
Hi, can you confirm that the patch fixes the issue for you?

**Comment by berserk-fury** [comment]
Hi @JulianKunkel 
Thank you for your quick response. I tested the patch and it works. The warning message is gone.
