### ISSUE TITLE
collective missing from script file options

### ISSUE THREAD

**Issue by adrianjhpc** [hpc/ior#372]
Hi,

"collective" seems to have dropped off the options that can be passed in the script file rather than at the command line. Is there any reason for this? If not I'll add it back in.

cheers

adrianj

**Comment by JulianKunkel** [comment]
You are right. Feel free to add it again:
        } else if (strcasecmp(option, "collective") == 0) {
                params->collective = atoi(value);
I think there was the issue to potentially move it out into the MPI-IO driver but then it turned out it is used elsewhere.

**Comment by adrianjhpc** [comment]
Does it need a pull request, or can I just commit to the master?

**Comment by JulianKunkel** [comment]
A PR is preferred.
