### ISSUE TITLE
allow md-workbench to run with phase 2-only, stonewalling, no wear-out

### ISSUE THREAD

**Issue by glennklockwood** [hpc/ior#387]
I want to run md-workbench such that it runs with stonewalling (`-w`), no wearout, and phase 2/benchmarking (`-2`) only, but this is explicitly prohibited by a runtime check.

I commented it out and, aside from the `stonewall-iter` output being a little misleading, it does work.  Can we make this an officially supported way of running?

The specific use-case for me is:
1. run `-1` as a standalone job - no stonewalling, no wear-out
2. run `-2` as a standalone job with stonewalling but no wear out - I am using md-workbench as a load generator and don't care if the final working set is not well defined
3. run `drm` from mpi-fileutils to clean up - `-3` doesn't work correctly with the stonewalled dataset leftover from step 2 above

**Comment by JulianKunkel** [comment]
The issue is that the cleanup phase cannot work properly. I suppose if the benchmark outputs a WARNING msg about this fact, then this will be fine.

**Comment by JulianKunkel** [comment]
Do you think the message is clear enough? Then merge :-)

**Comment by glennklockwood** [comment]
Thanks!  Message is clear and explained what took me an hour to figure out on my own.
