### ISSUE TITLE
Missing file closes in utilities.c

### ISSUE THREAD

**Issue by ryancaicse** [hpc/ior#404]
Hi, `fclose(out);` should be put before Line 896 to prevent resource leaks?
https://github.com/hpc/ior/blob/14deedfec48ce295dff683d15c1b194652bd6d08/src/utilities.c#L888-L898

**Comment by JulianKunkel** [comment]
Thanks for the review, agreed that would be better. While regarding the general flow of the code it doesn't matter, feel free to put in a PR alternatively, it will be fixed at some time.

**Comment by ryancaicse** [comment]
@JulianKunkel I create a PR. Thanks
