### ISSUE TITLE
mdtest on pvfs2 2.8.2

### ISSUE THREAD

**Issue by pegroman** [hpc/ior#412]
Hi! I tried to use mdtest on an old version of pvfs (2.8.2). pvfs installation was done in user space mode. 
When i try to run mdtest i get the following error:

"Process 0: FAILED in mdtest_run, Unable to create test directory path: No such file or directory
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0"

The command line that i use is: ./mdtest -d pvfs2:/mnt/pvfs2 -n 20 -i 2 -N 1
When I remove the "pvfs2:" prefix it works perfectly but it doesn't impact pvfs2. it only impacts the local file system.

Sorry for my poor level of English. Thanks in advance.

**Comment by JulianKunkel** [comment]
Could it be that under the PVFS2 namespace, there is no /mnt? MDTest will only attempt to create the last level directory (pvfs2 here).

**Comment by pegroman** [comment]
Julian! Thanks for reply. 
Could it be that under the PVFS2 namespace, there is no /mnt? --> Yes. You are right. I create the dir "mnt" under pvfs2 namespace (with ./pvfs2-mkdir) and works prefectly.
Again, thanks for the reply.
