### ISSUE TITLE
Spectrum Scale finegrainreadsharing hint performance updates

### ISSUE THREAD

**Issue by Pidad** [hpc/ior#418]
This issue is opened to make performance improvements for IBM Spectrum Scale. 

The IBM Spectrum Scale team is proposing we update the --posix.gpfs.finegrainreadsharing hint with our latest optimizations for small strided reads from a shared file in a parallel application. 

We are proposing code changes in aiori-POSIX.c under the existing HAVE_GPFS_FCNTL_H macro.  Additionally, configure.ac will be updated to enable this hint for the versions of IBM Spectrum Scale supporting these optimizations (versions 5.1.4+).

IBM Spectrum Scale versions 5.1.2 and 5.1.3 will use the earlier implementation of this hint.

**Comment by JulianKunkel** [comment]
Pidad, that sounds great. Please submit a PR with these changes!
