### ISSUE TITLE
why ior time is different

### ISSUE THREAD

**Issue by FrancesChien** [hpc/ior#43]
![image](https://user-images.githubusercontent.com/37571328/37639927-420a8736-2c4e-11e8-8652-7dd62d73d4c1.png)

why ior time is 174.62s while real time is only 1m29.592s...? the wrong ior time causes wrong throughput MiB/s... please anyone helps me... thank you so much!

**Comment by glennklockwood** [comment]
Can you share

1. the whole output (including the lines that begin wtih "`Began:`" and "`Finished:`", `Start time skew`, etc)
2. the version or commit number you used to build the binary that caused this?

Something seems a little strange here.

**Comment by ezickler** [comment]
This could also be a bug in the time deviation part of IOR, which should handle different system times on nodes. The time deviation gets only printed on verbose level 1. Can you please rerun this with -v so the time deviation is part of the output.

**Comment by FrancesChien** [comment]
We found it's caused by MPI_Time(), don't know why it is off by 2x in this case, with a physical server...  I tried to install ior with a VM then it's normal.

**Comment by glennklockwood** [comment]
That's strange.  Thanks for bringing this up though.  If others see it this is a good place to start looking.
