### ISSUE TITLE
maxTimeDuration does nothing

### ISSUE THREAD

**Issue by glennklockwood** [hpc/ior#44]
The `maxTimeDuration` option (`T`) is in the code and documentation, but has no functionality implemented.  Furthermore, it seems to describe the same functionality as `-D`/`deadlineForStonewalling`.

This vestigial code should be removed.

**Comment by JulianKunkel** [comment]
I checked it, actually it is like:
"max time in minutes executing repeated test; it aborts only between iterations and not within a test!"
While stonewalling aborts *within* a test.
I would keep the feature for now.

**Comment by glennklockwood** [comment]
Huh, OK.  I thought I looked for any references to the bits set when this flag is specified, and it was never even referenced in the code.  But if the code actually does something, I'm happy to close this out.
