### ISSUE TITLE
mmap support?

### ISSUE THREAD

**Issue by johnbent** [hpc/ior#45]
Would it be difficult to add an mmap backend?  That'd be pretty awesome.

**Comment by glennklockwood** [comment]
It would not; in fact, I have the read-only part of one written:

https://github.com/glennklockwood/ior_gkl/blob/posix-mmap/src/aiori-MMAP.c

The code was written before the mdtest merge though, so there are probably bits and pieces that need to be cleaned up.  The create/write part of the aiori, as well as support for different mmap modes (private, shared, anon, etc) would also need to be added.

**Comment by glennklockwood** [comment]
Thanks to @lidongyang for contributing this.  I created #53 to track the documentation for this new backend, but I didn't want to block the pull request on that.
