### ISSUE TITLE
mdtest doesn't say what units its results report

### ISSUE THREAD

**Issue by glennklockwood** [hpc/ior#452]
The output of mdtest doesn't actually report what its results' units are in. For example,

```
SUMMARY rate: (of 1 iterations)
   Operation                     Max            Min           Mean        Std Dev
   ---------                     ---            ---           ----        -------
   File creation               24392.579      24392.579      24392.579          0.000
   File stat                   50747.780      50747.780      50747.780          0.000
   File read                   36759.895      36759.895      36759.895          0.000
   File removal                50261.282      50261.282      50261.282          0.000
   Tree creation                2673.234       2673.234       2673.234          0.000
   Tree removal                 6168.094       6168.094       6168.094          0.000
```

People who use mdtest know that these results mean file creation happened at 24,392.579 create ops per second, but should we 
1. explicitly add "ops/sec" to either the table headings, or
2. add "ops/sec" as columns adjacent to each reported measurement, or
3. add a prefix or suffix line that just says "All values are ops/sec" before or after the summary section?

Option 3 might break the fewest extant mdtest output parsing scripts out there.

**Comment by JulianKunkel** [comment]
All sound reasonable.
How about we change:
> SUMMARY rate: (of 1 iterations)
to 
> SUMMARY rate (in ops/sec): (of 1 iterations)

**Comment by lvsszz** [comment]
SUMMARY rate (in ops/sec): (of 5 iterations)
   Operation                     Max            Min           Mean        Std Dev
   ---------                     ---            ---           ----        -------
   File creation               23415.162       4045.269      15115.641       8330.897
   File stat                   89213.225      57327.288      71783.401      12154.475
   File read                   49383.447      44397.218      47721.659       2090.005
   File removal                42661.757      31290.195      36195.051       5536.359
   Tree creation                 521.053        344.970        413.329         67.263
   Tree removal                  442.936        102.183        323.393        156.815

SUMMARY time (in ops/sec): (of 5 iterations)
   Operation                     Max            Min           Mean        Std Dev
   ---------                     ---            ---           ----        -------
   File creation                  18.985          3.280          7.792          6.658
   File stat                       1.340          0.861          1.094          0.181
   File read                       1.730          1.555          1.612          0.073
   File removal                    2.454          1.800          2.161          0.316
   Tree creation                   0.061          0.040          0.052          0.008
   Tree removal                    0.206          0.047          0.090          0.068

what is the difference between SUMMARY time and SUMMARY rate ？
