### ISSUE TITLE
RFE: Ramp-up time + measure over specific time for IOR

### ISSUE THREAD

**Issue by bolausson** [hpc/ior#463]
In some situations I have seen the infrastructure to take some time to settle/stabilize and it might be good to be able to exclude this periode from the measurement.

Would it be possible to implement a ramp up time after which the throughput will be measured for a specific time?
(FIO has a similar feature: [ramp_time](https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-ramp-time))

E.g. start an IOR write job which runs 15 minutes but only measure the throughput based on the IO that happened between minute 2 and minute 7. The IO metrics measured during minute 0 to 3 and 7 to the end of the run is excluded from the performance reporting.

The job should optionally be terminated after ramp-down time.

hree option would be required:
**ramp-up-time** -> Time periode to exclude from measurement
**measurement-periode** -> Time periode after ramp-up-time to be included in the measurement
**ramp-down-time** -> Time after measurement-periode when the just gets terminated wether it is complete or not

![IOR-ramp-up](https://github.com/hpc/ior/assets/10600678/7f162b92-3bf5-4830-a68f-d03edb5ab43a)

Greetings,
Bjoern

**Comment by JulianKunkel** [comment]
I understand your request. Somehow I would map this case to using iterations in IOR. It is not a perfect mapping - but it simplifies the story. 
For instance, using:
$ ./src/ior -i 3
I get:
```
access    bw(MiB/s)  IOPS       Latency(s)  block(KiB) xfer(KiB)  open(s)    wr/rd(s)   close(s)   total(s)   iter
------    ---------  ----       ----------  ---------- ---------  --------   --------   --------   --------   ----
write     823.70     3421.83    0.000292    1024.00    256.00     0.000041   0.001169   0.000003   0.001214   0   
read      8775       37036      0.000027    1024.00    256.00     0.000004   0.000108   0.000002   0.000114   0   
write     1062.66    4339       0.000230    1024.00    256.00     0.000016   0.000922   0.000002   0.000941   1   
read      9259       38836      0.000026    1024.00    256.00     0.000003   0.000103   0.000002   0.000108   1   
write     1060.51    4320       0.000232    1024.00    256.00     0.000015   0.000926   0.000002   0.000943   2   
read      9158       38836      0.000026    1024.00    256.00     0.000004   0.000103   0.000002   0.000109   2   
```
Hence, I could use iteration 1 as the measurement period.

If you want to stop after a specific time, you can provide a stonewalling time (deadline) using -D <TIME>.

Maybe that helps already?

**Comment by bolausson** [comment]
Yes I thought about this, but it is rather inconvenient if I need a long running job for the measurement.
Consider you want to gather the result over a 30 minute window, you would effectively end up with a 90 minute run in your example (or you would need many more short iterations and then "manually" average over all iterations of interest.
Furthermore, running three iteration is not the same as getting the result from a certain periode of a single run as you start to write to the files at offset 0 for each iteration instead of contineously writing to the file.

**Comment by JulianKunkel** [comment]
I thought further about it, I reckon with an IOR config file (use $ ior -f config) you can resolve this:
```
IOR START
# basic config
blockSize=1M
writeFile=1
transferSize=1M
keepfile=1
# ramp up, write 1000 segments, after 4 seconds stop forcefully
segmentCount=1000
deadlineforstonewalling=4
testfile=f-ramp-up
RUN

# Measurement period, here 2s, write more segments
segmentCount=10000
deadlineforstonewalling=2
testfile=f-measurement
RUN

# Ramp down
segmentCount=1000
deadlineforstonewalling=0
testfile=f-rampdown
RUN

IOR STOP
```

I'm actually not sure what benefit in your case you'd have with the ramp down phase -> in the example it will not stop forcefully. The measurement period will stop forcefully though -> until you remove deadlineforstonewalling.

**Comment by bolausson** [comment]
That should do the trick.
Thanks!
