### ISSUE TITLE
using ior as lib for c++ program

### ISSUE THREAD

**Issue by arauin** [hpc/ior#475]
When incorporating the ior header into a C++ program using the following method, I encounter an error:
```
extern "C"
{
#include "ior.h"
}
```

The error message I receive is:
```
In file included from ./build/ior/src/ior.h:34,
                 from src/ior_adapter.hpp:4,
                 from src/ior_adapter.cpp:1:
./build/ior/src/aiori.h: At global scope:
./build/ior/src/aiori.h:100:16: error: expected unqualified-id before ‘delete’
  100 |         void (*delete)(char *, aiori_mod_opt_t * module_options);
      |                ^~~~~~
 ```
 
Due to the delete keyword being reserved in C++, I must create a fork and rename each delete method. However, my preference is to utilize the main repository for building, and I would like to make ior usable in C++ if feasible.

As a reference, here is the structure definition:
 ```
typedef struct ior_aiori {
        void (*delete)(char *, aiori_mod_opt_t * module_options);
}
 ```

**Comment by JulianKunkel** [comment]
Thx for reporting. Based on my testing, the issue is now resolved! If you agree, then simply close the isuse.

**Comment by arauin** [comment]
Thanks for the fast fix
