### ISSUE TITLE
About supporting for HDF5 dataset filters

### ISSUE THREAD

**Issue by BingluCS** [hpc/ior#481]
I read the IOR support adding HDF5 dataset filters on the website 'https://www.hdfgroup.org/2022/03/parallel-compression-improvements-in-hdf5-1-13-1'. However, as mentioned inside, the function isn't merged into the main branch. Does the current IOR version and other branches support this function?

**Comment by JulianKunkel** [comment]
I haven't seen the code and, unfortunately, do not know where it could be available.
Maybe you can contact Jordan Henderson and check for access of the version.
Happy to merge it, if it is available.
It feels pointless to integrate filters completely new given there exists some code somewhere.

**Comment by BingluCS** [comment]
Okay, thanks for the reply.
