### ISSUE TITLE
IOR fsync options only allowed on POSIX backend

### ISSUE THREAD

**Issue by shanedsnyder** [hpc/ior#51]
MPIIO backend could support this option using `MPI_File_sync()`. HDFS backend looks like it currently implements this call as well.

We can probably just expand the "whitelist" of backends that support fsync to include those, and any new backend implementations capable of supporting sync operations. `fsync()` is already abstracted in the `aiori` interface so should be painless.

**Comment by JulianKunkel** [comment]
Good point. Now possible:
https://github.com/hpc/ior/commit/d938f0efe1b1b0b99b87d8a9f4fc7558d3376b7d
