### ISSUE TITLE
Stonewall in mdtest?

### ISSUE THREAD

**Issue by johnbent** [hpc/ior#58]
Julian added a very nice patch to IOR to add stonewalling with wearout (to correctly measure the straggler tail effect).  Is anyone working on doing this in mdtest?  Is it more challenging?

**Comment by JulianKunkel** [comment]
I have the patch for mdtest in my branch, however, it had many changes.
I will soon add a series of mini-patches to make it useful in the testing branch.

**Comment by JulianKunkel** [comment]
I integrated a rather big chunk of patch into the testing branch.
A basic version (supports IO500 case) is now there, but needs to store the output / number of iterations.

**Comment by JulianKunkel** [comment]
The mdtest version now appears to work as well.
It requires the -W (Time, e.g., 300) option. This option is only honored during the create phase of mdtest.
The -x option defines where the status (actual iteration number) is stored, example:
Create (max 300s):
./mdtest -I 200000 -W 300 -x stonewall-md.log -C
Stat (max file count according to stonewall-md.log)
./mdtest -I 200000 -x stonewall-md.log -T -v
Delete (max file count according to stonewall-md.log)
./mdtest -I 200000 -x stonewall-md.log -D -v

That should be the way to integrate into IO-500.

Info is communicated in one iteration that performs, e.g., -C, -T, -D as well (with delete mode, the status file is irrelevant, though).

Remember, I should not be set ultra high, as there are storage systems in which one process is 10x faster than others with file creation.
