### ISSUE TITLE
Julian's Roadmap for IOR

### ISSUE THREAD

**Issue by JulianKunkel** [hpc/ior#61]
The roadmap of changes I would apply to the testing branch.
Firstly include changes from: https://github.com/VI4IO/ior/commits/master
1) This covers a new testing option (IOR_FAKE_TASK_PER_NODES env variable) that allowed to reveal some bugs by virtually setting this value instead of autodetecting.
2) Fix self-referencing #20 
3) Minor issues.

Next, add a new testing bash script that runs various configurations (also using IOR_FAKE_TASK...)
and add quick tests to Travis for regression testing.

Then systematically include major changes from: https://github.com/JulianKunkel/ior-1/commits/master
1) Stonewalling option for mdtest
2) New: store actual stonewalling number to a file in write to allow usage during read phases.
3) Replace the option parser (needed for 4), at the moment this requires to get away from getopt() as some supercomputers I tested it on are unable to reset the parser when setting optind to 1. (BUG in getopt(), who would believe that...) Actually, the new parser is quite trivial, too...
4) Library option for IOR/MDTest (allowing to run the benchmarks concurrently).
This is at the moment a bit crude but will be improved further.
5) Check the existence of options such only relevant ones are used for mdtest/IOR see also #44 
Likewise, options relevant for one backend shall only be visible *if* the backend is chosen. The syntax is totally bloated at the moment.

Then cherrypick various commits like JSON output changes and such.

Further down the road, I see to work on the AIORI interface to provide a better abstraction, this will be a lengthier issue, but 
fixes: #35 
moving checks for backends into AIORI: #24

**Comment by glennklockwood** [comment]
This is a great list of features.  I propose we break this list up into separate issues so we can reference them separately as we more clearly define the next major IOR release.  If one falls behind or will need more time than the next release, then we can delay it.

Also, we should probably think of a deadline for the next major release so we aren't just constantly trickling in new features.  I propose something in ~February 2019 based how much of my time I can contribute towards testing, but if more people are willing to pitch in, we can move that up.

**Comment by JulianKunkel** [comment]
Agreed, it was not a good idea, to post all changes here.

In the testing branch what is done is:
* Integration of all features pending in my branch(es)
* Simpler testing
* Library versions
* Various minor issues like compiler warnings / Valgrind complains
* MDTest: basic stonewalling (to be improved)

Pending in order, I would do them:
1. IOR: Store actual stonewalling number to a file in write to allow usage during read phases.
2. MDTest: Fix stonewalling to cover more cases 
3. Integration of JSON output from @ezickler 
4. Add tests for other than POSIX backends.
5. Argument cleanup: 
a) Ordering of arguments into semantic groups with descriptions and that work together
b) Move some checks into AIORI backend
6. Fix AIOR for mdtest

I will add separate issues for the major features 

Generic feedback or tests to the current versions would be welcome.

**Comment by glennklockwood** [comment]
How do you feel about the status of this particular issue?  Most of the features are in master and should be available for the 3.2 release.  A couple (like json output, AIORI support for mdtest) aren't quite there yet.  Should we just break the remaining items out as separate issues and close this?  Or should we keep this open?
