### ISSUE TITLE
Option parser

### ISSUE THREAD

**Issue by JulianKunkel** [hpc/ior#64]
I'm exploring the use of a new option parser that changes the handling of the option parsing.
Particularly such that the AIORI plugins can provide their own rich set of options, too. 
The changes are visible in 08351913726ef84a3a6

The two option groups (default tool, then plugin) are separated by --, e.g.:
./src/mdtest -a DUMMY -I 1 -- -c 10000 

An example is provided in Dummy, some stuff in RADOS but untested.
At the moment it is *only* used in mdtest.

@shanedsnyder
Could you have a look if that is works for RADOS, too? (I believe so).

**Comment by ezickler** [comment]
God idea. I thought of some thing like this also, but wasn't sure about the command line syntax. This -- solution, is it some thin you came up with or is it a common way to handle two separate sets of parameters? 
I think following commonly used approaches is especially important when it comes to user interface. Even with command lines.

**Comment by shanedsnyder** [comment]
@JulianKunkel I did have a look and everything looks good. I added a couple more RADOS-specific command line options as part of PR #76 and it all appears to be working fine.

It might be worth documenting somewhere that the backend-specific options are only supported on the command line, unless I'm mistaken. Some users may expect them to be supported in the IOR config files.

**Comment by JulianKunkel** [comment]
All done. Well -- comes from the UNIX tools to ignore options, here it is not quite the same but we ignore them in the first parser.
