### ISSUE TITLE
Echo commit hash used for cloning IOR and MDREAL

### ISSUE THREAD

**Issue by vnobody** [hpc/ior#69]
Hello.
Probably it would be good to echo commit hashes while cloning IOR and MDREAL repositories in prepare.sh? Currently it clones the repos and checks out the latest commits by default. Reason for this change might be, when testing multiple systems in different days/months and installing fresh version, there might be a situation, that results are with big difference and users might wonder why this happened. In that case, the reason will be, that different versions of IOR or MDREAL were used.

**Comment by glennklockwood** [comment]
+1.  The IOR/mdtest master branch is not stable, so not specifying a specific commit to check out can produce IO-500 builds that simply don't run.

**Comment by glennklockwood** [comment]
I think you might be filing this issue to the wrong repo.  Did you mean to submit this to the io500 repository?

**Comment by vnobody** [comment]
Thanks for mentioning. Wrong repo.
